### ISSUE TITLE
The 1.3.2 release does not have LICENSE file packaged

### ISSUE THREAD

**Issue by martenson** [compomics/ThermoRawFileParser#103]
This affects bioconda package build process at https://github.com/bioconda/bioconda-recipes/pull/26729.

the 1.3.2 doe snot have it https://github.com/compomics/ThermoRawFileParser/releases/download/v1.3.2/ThermoRawFileParser.zip
the 1.2.3 has the LICENSE file https://github.com/compomics/ThermoRawFileParser/releases/download/v1.2.3/ThermoRawFileParser.zip

**Comment by caetera** [comment]
Hi @martenson, I will make a note to add it during the build. Not sure how and why it get lost. The next release should include the LICENSE.
