### ISSUE TITLE
FAIMS compensation voltage is missing in mzML

### ISSUE THREAD

**Issue by markmipt** [compomics/ThermoRawFileParser#104]
Hi,

The output of ThermoRawFileParser does not contain FAIMS compensation voltage information.

At the same time, it presented in the output of msconvert and looks like:
` <cvParam cvRef="MS" accession="MS:1001581" name="FAIMS compensation voltage" value="-50.0"/>`

I can share raw file if you need it for fix.

Regards,
Mark

**Comment by caetera** [comment]
Hi Mark,

the following commit adds FAIMS CV to mzML 2d7abcd7712d9015c695464a36787b0f20f1c1df

**Comment by markmipt** [comment]
Thanks! It works fine for FAIMS data now. However, output always contains line with "FAIMS compensation voltage" = 0.0 for the  standard data with no FAIMS. Is it expected behavior? By the way, msconvert doesn't add these lines for the data with no FAIMS.

Regards,
Mark

**Comment by nielshulstaert** [comment]
This is fixed in release 1.3.3. It should report a value only when the FAIMS CV is on.
