### ISSUE TITLE
Why are the metadata options exclusive?

### ISSUE THREAD

**Issue by martenson** [compomics/ThermoRawFileParser#105]
Hi,

I have a question regarding the `-m, --metadata=VALUE` option. The possible values are `0 for JSON, 1 for TXT`. However upon inspection it is clear the `json` and `txt` selections are not format output choices, because the files have different contents with only small overlaps.

Why is this the case? In our use case we want to preserve all the metadata - the info in json for public repository deposition and the info in txt for downstream analysis steps.

Is it realistic to rerun the parser on the same input to gain both of these metadata files? Is there a better option?

**Comment by caetera** [comment]
Hi @martenson,

I am afraid, I cannot answer your "why" question, maybe @nielshulstaert or @ypriverol can answer to it.
However, it is possible to have new option (for example, `2`) to have both JSON and TXT metadata. The only complication for now, I cannot come with a obvious and pretty solution to have user-defined path for both of files (i.e. if both metadata types will be exported the value of `--metadata_output_file` becomes dubious).

**Comment by martenson** [comment]
You could e.g. replace the `-m` and `-c` options with two path options, one for the "deposition metadata" and one for the "experiment metadata". If the option is present and has a valid path value it will create the corresponding output file. That would also clarify the txt/json confusion, so the option wouldn't look like data format choice anymore.

**Comment by caetera** [comment]
Yes, that is good option, I will work on it. Although it might be not that fast, since I need to be sure it is backwards compatible.

**Comment by nielshulstaert** [comment]
There is indeed little overlap between the 2 format options, we either need to make it more clear in the documentation or have the same metadata in both. Initially only the text format was available. @ypriverol you've worked on the json format, what do you think?

**Comment by edeutsch** [comment]
I had always assumed that the content of the information was the same in the json and the text, just two different ways of expressing it. So I'm surprised to hear the contained metadata is different. It seems highly beneficial to me have all metadata in one location rather than two different subsets in two different files. I would personally advocate all metadata in the JSON file, since JSON seems universally trivially read in any language these days..

**Comment by nielshulstaert** [comment]
Hi @edeutsch , @ypriverol , @martenson ,

This table shows the metadata entries for both JSON and TEXT formats I would like to add in the next release. This way, both formats contain the same data and it should be backwards compatible. I tried to find appropriate CV terms for all of the fields, let me know if this looks good or if you have other suggestions.

| **JSON**                                            | **TXT**                      | **Empty check** |
| ----------------------------------------------- | ------------------------ | ----------- |
| **FileProperties**                                  |                          |
| Pathname (NCIT:C47922)                          | RAW file path            |             |
| Version (NCIT:C25714)                           | RAW file version         |             |
| Content Creation Date (NCIT:C69199)             | Creation date            |             |
| Description (NCIT:C25365)                       | Description              | x           |
| **InstrumentProperties**                            |                          |
| Thermo Scientific instrument model (MS:1000494) | Instrument model         |             |
| instrument attribute (MS:1000496)               | Instrument name          |             |
| instrument serial number (MS:1000529)           | Instrument serial number |             |
| Software Version (NCIT:C111093)                 | Software version         |             |
| firmware version (AFR:0001259)                  | Firmware version         | x           |
| **MsData**                                          |                          |
| Number of MS1 spectra (PRIDE:0000481)           | Number of MS1 spectra    |             |
| Number of MS2 spectra (PRIDE:0000482)           | Number of MS2 spectra    |             |
| Number of MS3 spectra (PRIDE:0000483)           | Number of MS3 spectra    |             |
| MS min charge (PRIDE:0000472)                   | MS min charge            |             |
| MS max charge (PRIDE:0000473)                   | MS max charge            |             |
| MS min RT (PRIDE:0000474)                       | MS min RT                |             |
| MS max RT (PRIDE:0000475)                       | MS max RT                |             |
| MS min MZ (PRIDE:0000476)                       | MS min MZ                |             |
| MS max MZ (PRIDE:0000477)                       | MS max MZ                |             |
| **ScanSettings**                                    |                          |
| scan start time (MS:1000016)                    | Scan start time          |             |
| mass resolution (MS:1000011)                    | Mass resolution          |             |
| mass unit (UO:0000002)                          | Units                    |             |
| Number of scans (PRIDE:0000478)                 | Number of scans          |             |
| MS scan range (PRIDE:0000479)                   | Scan range               |             |
| Retention time range (PRIDE:0000484)            | Time range               |             |
| Mz range (PRIDE:0000485)                        | Mass range               |             |
| fragmentationType                               | Fragmentation types      |             |
| **SampleData**                                      |                          |
| sample name (MS:1000002)                        | sample name              | x           |
| sample number (MS:1000001)                      | sample ID                | x           |
| type (NCIT:C25284)                              | sample type              | x           |
| Comment (NCIT:C25393)                           | sample comment           | x           |
| Vial (NCIT:C41275)                              | sample vial              | x           |
| sample volume (MS:1000005)                      | sample volume            | x           |
| injection volume setting (AFR:0001577)          | sample injection volume  | x           |
| Row (NCIT:C43378)                               | sample row number        | x           |
| dilution factor (AFQ:0000178)                   | sample dilution factor   | x           |

**Comment by nielshulstaert** [comment]
JSON and TEXT output formats output the same metadata fields in release 1.3.3

**Comment by martenson** [comment]
Thank you very much for such a quick response. Marvelous! 🎉
