### ISSUE TITLE
Multiple Dockerfiles/images seem to confuse new users

### ISSUE THREAD

**Issue by RalfG** [compomics/ThermoRawFileParser#113]
Is there a specific reason to have two Dockerfiles in this repository, next to the available images through bioconda/biocontainers? If not, I would advocate to simplify the situation and refer users to the biocontainers image only, or at least make the Docker section in the README a bit clearer.

**Comment by nielshulstaert** [comment]
Thanks for the good suggestion, these files are there from before the biocontainers image was available. I'll remove the Dockerfile_basic and tell people to use the biocontainers image. @ypriverol do you still use the other Dockerfile?

**Comment by ypriverol** [comment]
I originally intended this to have something close to the repo. Now it doesn't make sense because, as @RalfG suggested, the bioconda container is the main option. Feel free @nielshulstaert to remove the docker file.

**Comment by nielshulstaert** [comment]
I removed the obsolete docker files, thanks again for the suggestion.
