### ISSUE TITLE
Zip a folder

### ISSUE THREAD

**Issue by sorenwacker** [compomics/ThermoRawFileParser#114]
Lol, I am really happy for this package. However, I just made the mistake and unzipped the file in my home directory. It will take me a while to clean that up again.

**Comment by caetera** [comment]
Hi @soerendip, thank you for using ThermoRawFileParser.
Your suggestion is to put a folder inside of release zip, instead of individual files. Did I get it right?

**Comment by soerendip** [comment]
Yes, that is correct.
