### ISSUE TITLE
mzML to parquet?

### ISSUE THREAD

**Issue by soerendip** [compomics/ThermoRawFileParser#115]
I saw you are introducing parquet as output format. It would be great if the user would be able to use mzML as input and convert it to that format. Great tool!!

**Comment by nielshulstaert** [comment]
Hi @soerendip thanks for using the TRFP! Conversion from a non-RAW format to other formats is not really something we're planning to include. There are mzML readers available in a lot of languages that you could use as a starting point. Let us know if you want more fields in the parquet output though.
