### ISSUE TITLE
MZ Values not sorted after conversion and peak picking

### ISSUE THREAD

**Issue by SteffenHeu** [compomics/ThermoRawFileParser#117]
OS: Windows 10 64 bit
Raw file parser version: ThermoRawFileParserGUI-1.6.0

Settings:
![grafik](https://user-images.githubusercontent.com/37407705/116659006-333e3900-a991-11eb-99b5-fbfeda401319.png)

When converting an Orbitrap Exactive raw data file, negative acquisiton mode not all m/z values are sorted. I'm not sure if it's actually a bug and m/z values are not guaranteed to be sorted, but every other value seems to be sorted ascendingly. 

See here:
![grafik](https://user-images.githubusercontent.com/37407705/116658447-3d136c80-a990-11eb-9b1d-92807a0b01d8.png)

This is in scan number 1/index = 0.

Is it expected/unexpected behaviour?

**Comment by nielshulstaert** [comment]
Hi there is no sorting in the TRFP code. You could try using msconvert and see if you get the same behavior.

**Comment by tomas-pluskal** [comment]
I think the sorting of the m/z values is not strictly defined in the mzML standard specification, but it is sort of expected, because other tools do that and it "makes sense" to keep the data sorted by m/z. I also believe that msConvert always produces spectra sorted by m/z values, but it will be interesting to see if @SteffenHeu tests it on the same Orbitrap Exactive raw data file as above.

**Comment by SteffenHeu** [comment]
Also happens with MSConvert if only "vendor peak picking" is applied. If An intensity threshold of 1 is set, the issue does not occur (at least for the given file). However, the actual intensity of the not-sorted m/z is not 0.

I have realised i forgot the link to the files in my initial post:
https://uni-muenster.sciebo.de/s/j4POPaWzWsjllkz 
This includes the raw file, the Raw file parser file (*-trfp) and two MSConvert mzml files with and without intensity cutoff in case you want to look into it.

MSConvert Version: 3.0.21010-71ac35ded (developer build)
Conversion settings and acutal values:
![grafik](https://user-images.githubusercontent.com/37407705/118675395-dc42bb80-b7fa-11eb-8a19-ea526f6ff984.png)

**Comment by caetera** [comment]
Hi @SteffenHeu , I had a quick look at the file you have provided, scan 1 does not have the any peaks between 747 - 748 (neither raw, nor TRFP, nor MSC versions). Is it the correct file/scan?

@nielshulstaert , should we just add sorting of masses and intensities? I did a quick test, it adds <0.5% to execution time

**Comment by SteffenHeu** [comment]
Hi caetera, 
it seems that my debugger (or our data model) fooled me. 

The scan start time is 0.64536 in the trfp file with this spectrum id:
`<spectrum id="controllerType=0 controllerNumber=1 scan=38" index="37" defaultArrayLength="1204">`

Sorry for the inconvenience.

**Comment by SteffenHeu** [comment]
Thank you!
