### ISSUE TITLE
Semantic arguments for formats

### ISSUE THREAD

**Issue by sorenwacker** [compomics/ThermoRawFileParser#121]
Hi,

who about changing the numbers to human readable format. I have to look up which format is which number each time I use the parser (after working on something else). To see what number I have to provide. 

How about changing e.g.:

    ThermoRawFileParser.exe -i test.raw -f 3 

to 

    ThermoRawFileParser.exe -i test.raw -f parquet

And 

    ThermoRawFileParser.exe -i test.raw -f 1

to

    ThermoRawFileParser.exe -i test.raw -f mzML
 
and make it independent of the letter case.

Same for `--metadata`.

I find 

    ThermoRawFileParser.exe -i test.raw -m txt

much easier to remember than that 

    ThermoRawFileParser.exe -i test.raw -m 1

will create a txt an not a json file.

Cheers

**Comment by caetera** [comment]
Implemented in f1e9ed2

**Comment by sorenwacker** [comment]
Nice!
