### ISSUE TITLE
RawFileReader .NET assembly page offline

### ISSUE THREAD

**Issue by tobiasko** [compomics/ThermoRawFileParser#124]
Dear compOMICS,

we realised that the RawFileReader page on planet orbitrap went offline. see https://planetorbitrap.com/rawfilereader Are you aware of any changes with respect to how Thermo is distributing the CommonCore dlls / .NET assembly in the future? Is Jim still the contact point at Thermo? What is the latest version? Your repo contains 4.0.26

Thx in advance,
Tobi

**Comment by caetera** [comment]
Hi Tobias,

(although I am not part of Compomics), to the best of my knowledge Thermo decided to close PlanetOrbitrap portal and replace it with "better" one - AnalyteGuru - https://www.analyteguru.com/t5/Knowledgebase/Welcome-Planet-Orbitrap-Members/ta-p/13999.
There are some information regarding the RawFileReader on AnalyteGuru - https://www.analyteguru.com/t5/Scientific-Library/Raw-File-Reader/ta-p/8870; it is not very recent, but Jim seems to be the contact still.

Off note, the latest release of TRFP uses RawFileReader 5.0.0.71

**Comment by tobiasko** [comment]
Hi @caetera,

AnalyteGuru? Hail to the marketing department at Thermo Fisher! Yes, that is Jims old presentation from ASMS Atlanta 2019, but I can't find anything else. BTW: Do you know which recent .NET frameworks are compatible with the CommonCore dlls (SDKs, runtime). I am pretty confused by the .NET ecosystem and what is currently best practice.

Greetings,
Tobi

**Comment by caetera** [comment]
Hi @tobiasko,

I am certainly not the most reliable source of information on .NET ecosystem, however, as far as I can see, the latest versions of CommonCore (starting from 5.0.7) are provided in NetFramework 4.7.1 and NetStandard 2.0 versions. We build TRFP with NetStandard one, it _should_ allow better compatibility between different platforms. Here is the information about different standards and their support by different .NET implementations https://docs.microsoft.com/en-us/dotnet/standard/net-standard
It also states, that after .NET 5; NetStandards become obsolete; in short, it does not make the situation much more clear.

**Comment by caetera** [comment]
I will close the issue for now
