### ISSUE TITLE
Precursor intensity (the final issue)

### ISSUE THREAD

**Issue by caetera** [compomics/ThermoRawFileParser#125]
There is a long-lasting story of missing precursor intensity in TRFP (see #78 #47) and it should (finally, fingers crossed) come to an end, since this feature will be added to a next release.
It probably makes most sense to determine the precursor intensity in the same way as msconvert.
Looking at the msconvert code I can find two methods for precursor intensity calculation.

1. (recent versions) Precursor intensity is calculated as a total ion intensity in the isolation window (i.e. take the intensity of all signals in the isolation window and sum them up)
2. (older versions) Precursor intensity is calculated as at peak height on the XIC of precursor ion at the moment of sampling (i.e. the XIC corresponding to precursor is built with default parameters, that are dependent on the ms analyzer used, and then the height at the sampling RT is used as precursor intensity - it is not the maximum height of the XIC peak itself).

I am not sure why the method was changed in msconvert and I am not sure which one is preferable.
If you have any thought on that matter (or don't have any), please, feel free to speak.

I will tag people who were active in previous discussions about precursor intensity (@edeutsch @rmflight @hbarsnes) , you can tag someone who can have an important input.

**Comment by hbarsnes** [comment]
@caetera Thanks for looking into this! I do not have any strong opinions on which method is the best one, but I would argue for using the same as msconvert, if only to make the differences between the resulting files from the two tools as small as possible.

**Comment by edeutsch** [comment]
I agree with that argument.

Tagging @chambm in case he wishes to read the above and provide a opinion.

**Comment by chambm** [comment]
The main reason for the change was to use previously retrieved peaks if possible instead of reading them in again. But I don't recall why I switched to summing the intensities instead of using the base peak. Both methods are flawed due to isolation window interference and only looking at a single MS1. I hope nobody's using it for serious quantitation. :sweat_smile:

**Comment by caetera** [comment]
Thank you all for the feedback. I will use the **recent** method, i.e. summing the intensities in that case

**Comment by caetera** [comment]
I have a build that includes precursor intensity; in my tests the output is quite similar to msconvert (i.e. average error of ~0.1% and max error of ~2% in the worst test). I hope it can be accounted for some sort of "rounding" error, and since it is kind of rough estimation anyway it might not be critical. If somebody wants to give it a try, I have shared the build https://syddanskuni-my.sharepoint.com/:u:/g/personal/vgor_bmb_sdu_dk/EeJ50TcZl35OpplVv2ZT7hEBL4gudhEsGoFz1UHgOJXzLw?e=v67e4L

@chambm I have to use the center of isolation window (selected mass) rather then monoisotopic mass to get close to msconvert's output. Is it expected?

**Comment by chambm** [comment]
ProteoWizard's Thermo reader sums the intensity in the MSn's isolation window to get the precursor intensity, so yes using some width around the isolation window center would be equivalent.

**Comment by caetera** [comment]
Has been included in release 1.4.0
