### ISSUE TITLE
The given key 'PaperSprayIonization' was not present in the dictionary

### ISSUE THREAD

**Issue by abdelq** [compomics/ThermoRawFileParser#128]
While trying out conversion of a raw file from a Thermo Fisher Scientific VeriSpray PaperSpray instrument, I noticed the exception in the title. I would have submitted a PR, but I don't know where the `accession` value comes from.

```
IonizationModeType.PaperSprayIonization, new CVParamType
{
    accession = "MS:???????",
    name = "paper spray ionization",
    cvRef = "MS",
    value = ""
}
```

**Comment by caetera** [comment]
Hi @abdelq ,
Thank you for your interest in ThermoRawFileParser. The accession is defined in PSI-MS controlled vocabulary (CV).
The vocabulary is maintained in https://github.com/HUPO-PSI/psi-ms-CV in OBO format. After a brief lookup, it seems like _paper spray ionization_ is not present yet in the vocabulary. You can either add a new term in the vocabulary (you can just do PR there with the update), or check if some synonym already available in the vocabulary can be used instead.

As a side note, if you add a new CV term, there will be some delay between the time it will be accepted to the PSI-MS CV and the updated version of CV will reach the common software tools and libraries. For example, it might mean that the resulting files will be considered invalid by older versions of proteowizard (and all tools using it).
Just to clarify, I am fine with adding support for PaperSpray to TRFP, just want to make you aware that there might be issues with downstream analysis of the resulting mzML files.

**Comment by edeutsch** [comment]
Hi everyone, the new term is merged into the CV:
https://github.com/HUPO-PSI/psi-ms-CV/pull/100/files
