### ISSUE TITLE
Is possible to extract PDA and MS data from mzml files to csv?

### ISSUE THREAD

**Issue by ZewSam** [compomics/ThermoRawFileParser#134]
Hi, I have a hard time to extract the PDA and MS peak list from mzML file for analysis.  Is there any way to extract PDA and MS data from mzML to csv?

**Comment by ZewSam** [comment]
> 

Thanks for your response.  I am able to convert my RAW file to mzml file.  I would like to export PDA data and MS data for multivariate analysis in other software, like SPSS, MATLAB.  Because these software cannot read mzml file directly, I am just wondering if there is a way to extract the PDA data and the peak list of MS data along retention time into other formats (such excel, csv, etc.) from mzml, so I can import to the statistic software.  Thanks again.

**Comment by ZewSam** [comment]
Hi @caetera , thank you so much for the inspiration.  This sample script is very helpful.

**Comment by caetera** [comment]
I will close the issue now
