### ISSUE TITLE
Wrong assignment of MS3 to MS2

### ISSUE THREAD

**Issue by MatthewThe** [compomics/ThermoRawFileParser#139]
Again thanks for this wonderful package!

We noticed some MS3 scans being attributed to the wrong MS2 scan.

It seems to be a result of an unfortunate partial string match here: 

https://github.com/compomics/ThermoRawFileParser/blob/6e133e47a814d43b5a7c988c71c93d530ff54936/Writer/MzMlSpectrumWriter.cs#L30

https://github.com/compomics/ThermoRawFileParser/blob/6e133e47a814d43b5a7c988c71c93d530ff54936/Writer/MzMlSpectrumWriter.cs#L2156-L2159

For example, we have an MS2 with the following filter string
`MS2 scan=2298: FTMS + c NSI d Full ms2 623.0950@cid35.00 [166.0000-1257.0000]`

It gets assigned these two MS3 spectra:
`MS3 scan=2300: FTMS + c NSI d Full ms3 623.0950@cid35.00 500.0461@hcd55.00 [100.0000-1000.0000]`
`MS3 scan=2334: FTMS + c NSI d Full ms3 894.4648@cid35.00 623.0950@hcd55.00 [100.0000-1000.0000]`

Note that the match occurs on `623.0950`, but it is incorrect in the second case which actually belongs to this MS2 spectrum:
`MS2 scan=2332: FTMS + c NSI d Full ms2 894.4648@cid35.00 [241.0000-2000.0000]`

**Comment by caetera** [comment]
Hi @MatthewThe,
thank you for reporting this issue. The way spectra are assigned to parents has been changed completely in a recent beta (see #126 ). Could you check if the error still exist in the version I have shared there? You can also share the problematic raw file with me if it is more convenient.

**Comment by MatthewThe** [comment]
Yes, that seems to have fixed it. Thanks a lot!
