### ISSUE TITLE
v1.4.1 docker image

### ISSUE THREAD

**Issue by wholtz** [compomics/ThermoRawFileParser#145]
Thanks for getting v1.4.1 released! What needs to happen to get a new docker image generated? I looked into https://github.com/BioContainers/containers to see if I could generate a PR to make it happen, but I couldn't seem to find a Dockerfile for this project within the biocontainers git repo.....

**Comment by caetera** [comment]
Hi @wholtz,
AFAIK, new releases should in principle be picked and built. There is a bioconda-reciept https://github.com/bioconda/bioconda-recipes/tree/master/recipes/thermorawfileparser that might also be of some help.
Maybe @ypriverol or @bgruening can answer this better.

**Comment by wholtz** [comment]
PR submitted for review: https://github.com/bioconda/bioconda-recipes/pull/37652

**Comment by wholtz** [comment]
Updating the bioconda recipe did result in a new docker image on https://quay.io/repository/biocontainers/thermorawfileparser?tab=tags
