### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by bgruening** [compomics/ThermoRawFileParser#15]
Hi!

Thanks for this great project. It would be nice if you could integrate a LICENSE file.

Thanks!!!

**Comment by ypriverol** [comment]
I will do it.

**Comment by ypriverol** [comment]
license added.

**Comment by caetera** [comment]
What about the license for non-thermo code?
The current license file seems to be only for the Thermo .NET libraries. Will the same rules apply for all the code?
To put it in plain words, what if I want to reuse the code from, let's say mzML writer in my own project?

**Comment by ypriverol** [comment]
Good point, We can probably add a second license to the project.
