### ISSUE TITLE
Docker Image build for linux/amd64 and linux/arm64/v8

### ISSUE THREAD

**Issue by gimse** [compomics/ThermoRawFileParser#151]
This would make it possible to run the docker image on Mac and Raspberry pi.

Best regards 
Gimse

**Comment by caetera** [comment]
Hi @gimse ,
thank you for your interest in ThermoRawFileParser.

Currently, docker images are built through bioconda-recipes: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/thermorawfileparser; each update of the recipe should generate a new biocontainer image in https://quay.io/repository/biocontainers/thermorawfileparser?tab=tags (as I can see they are linux/amd64 already and are tested on MacOS already). As to arm64 support, the main dependency of TRFP is Mono - i.e. if *it* runs Mono, *it* should be able to have TRFP. I can find this base image: https://hub.docker.com/r/arm64v8/mono/, thus, I believe it should be possible to have arm64 supported. Please, be aware of some sort of bug with 6+ branch of Mono that prevents it from processing files provided as symlinks (see #108)

Honestly, I do not feel very confident with docker images, especially, if it has to be done "in the right way", thus, any help is highly appreciated.  I hope the information above is still useful.

**Comment by hechth** [comment]
@gimse did this answer already help you further? If you encounter any problems with the bioconda package or biocontainer let me know.

**Comment by caetera** [comment]
Close for now, please, feel free to reopen if necessary
