### ISSUE TITLE
[Exploris] Issue with EASY-IC lockmass calibration/filtering

### ISSUE THREAD

**Issue by lfnothias** [compomics/ThermoRawFileParser#153]
I am running into an issue when converting a .raw file from an Exploris 120 to the mzML format with ThermoRawFileParser.
The mzML file is converted successfully and lockmass is *presumably* applied to the generated data. However the lockmass (202.0778) is not filtered out from the MS1 and MS2 scans like it is the case when examining the spectra with XCalibur and FreeStyle. I tried to look into the different parameters of ThermoRawFileParser, but without success. Any insight about how to get the calibrated/filtered data from the .raw file to .mzML with ThermoRawFileParser ?

Thanks in advance for the support.

The raw and resulting mzML files here (as well as mzXML from RawConverter see below): 
[https://drive.switch.ch/index.php/s/y35gSbwxpn8sk8s](https://drive.switch.ch/index.php/s/y35gSbwxpn8sk8s)

Converted with the following parameters:

```
ThermoRawFileParser.exe" -i 20230217_RMG_RMG_1_conditioning_26.raw --ignoreInstrumentErrors
```

NB1: trying to convert the same file with MSConvert fails with an error. 
```
Starting...
Opening file "J:\20230217_RMG_RMG_1_conditioning_26.raw" for read...
Calculating SHA1 checksum...
Processing...
Failed - System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at pwiz.analysis.SpectrumListFactory.wrap(MSData* , vector<std::basic_string<char\,std::char_traits<char>\,std::allocator<char> >\,std::allocator<std::basic_string<char\,std::char_traits<char>\,std::allocator<char> > > >* , IterationListenerRegistry* )
   at pwiz.CLI.analysis.SpectrumListFactory.wrap(MSData msd, IList`1 wrappers, IterationListenerRegistry ilr)
   at MSConvertGUI.MainLogic.processFile(String filename, Config config, ReaderList readers, Map`2 usedOutputFilenames)
   at MSConvertGUI.MainLogic.Go(Config config, Map`2 usedOutputFilenames)
```

NB2: trying converting the same file with RawConverter produces an mzXML file with lockmass removed (trying mzML doesn't create an output file). 
[(http://fields.scripps.edu/rawconv/](http://fields.scripps.edu/rawconv/)

**Comment by caetera** [comment]
Hi @lfnothias,

thank you for using ThermoRawFileParser. Lock mass is applied at the instrument side, i.e. the spectra are already recalibrated in the raw file, and, thus, TRFP does not perform any processing of it. Lock mass is a part of the, so-called, _reference_ peak data, it is included in the output by default (similarly to how it is done in MSConvert), you can use `-x, --excludeExceptionData` to exclude it. Please, note, however, that this option excludes not only lock mass (and other _reference_ data) but also some other peaks (for example, artifacts of FT process, splits, etc), all such peaks are marked by the instrument as _exception_. There is no option to exclude them separately. Usually, it is just a couple of such peaks per spectrum, and, thus, they do not make a huge difference for any downstream data analysis. Marking _exclusion_ and _reference_ peaks and adding/removing them from the scan data are performed by the instrument itself and the raw file reading libraries, respectively; TRFP just request and reads the data provided, i.e. does not modify it in any way. 

The scans that have lock mass applied will have the word **lock** in their scan filter (this parameter is included in mzML output).

Please, let me know if it answers you question.

**Comment by lfnothias** [comment]
Wonderful ! Thanks a lot for the support. That works beautifully ! With that option the EASY-IC lockmass is removed from MS1 and MS2 scans in the mzML produced. I checked both for POS and NEG mode.
Eyeballing few MS2 spectra, it seems that there might be residual mass observed at very low level for m/z 201.0708 in negative mode and 201.128 in pos mode, but it seems neglectable.
<img width="1264" alt="neg_with_excludeExceptionData" src="https://user-images.githubusercontent.com/22830047/220884318-9b7879af-bfa4-441b-8052-33b3f4c3ac97.png">
<img width="1264" alt="neg_without_excludeExceptionData" src="https://user-images.githubusercontent.com/22830047/220884322-bc9e9c9b-4847-49e1-a469-78423511b54d.png">
<img width="1264" alt="pos_with_excludeExceptionData" src="https://user-images.githubusercontent.com/22830047/220884336-d9f33d78-6c04-473c-8e61-c964f1496be1.png">
<img width="911" alt="pos_without_excludeExceptionData" src="https://user-images.githubusercontent.com/22830047/220884341-63671a0d-212f-4f83-a698-14ccd9571c32.png">
