### ISSUE TITLE
No dissociation method detected 

### ISSUE THREAD

**Issue by ypriverol** [compomics/ThermoRawFileParser#159]
Im trying to process the following file 09apr2014_HESC_SCX8to12_RP4.raw (ftp://massive.ucsd.edu/MSV000086944/raw/raw/09apr2014_HESC_SCX8to12_RP4.raw) and when I convert it to mzML is not exporting the dissociation method.

**Comment by caetera** [comment]
Hi @ypriverol,

I have processed the file with versions 1.4.0 and 1.4.2 both seem to produce a valid mzML file, i.e. every MS2 scan has an `<activation>` element and the fragmentation type is set to HCD - `<cvParam cvRef="MS" accession="MS:1000422" value="" name="beam-type collision-induced dissociation" />`

Did I understand your problem correctly?

**Comment by caetera** [comment]
Closed for now, please, feel free to reopen if necessary
