### ISSUE TITLE
Missing isolation width offsets for SPS masses

### ISSUE THREAD

**Issue by radusuciu** [compomics/ThermoRawFileParser#162]
Hi, I recently encountered an error when trying to process some TMT SPS-MS3 datasets with OpenMS (see: https://github.com/OpenMS/OpenMS/issues/6856), and I believe it is related to the fact that ThermoRawFileParser outputs a constant -0.5 value for both the upper and lower isolation width offsets. Changing the sign of the values is sufficient to allow processing to continue (though I'm not yet convinced this is a good idea..).

I saw that you've indicated [in a comment](https://github.com/compomics/ThermoRawFileParser/issues/81#issuecomment-699518794) that these values are not available in the raw file, but was wondering if that is still the case. `msconvert` seems to output values but I am not familiar enough with the raw->mzML conversion process to know if that ThermoRawFileParser can access the same underlying data.

**Edit:** seem like `msconvert` may also not deal with these cases very well: https://github.com/ProteoWizard/pwiz/issues/2062

Thank you for your continued work on this project!

**Comment by caetera** [comment]
Hi @radusuciu,

thank you for using ThermoRawFileParser.

Looking at the snippet you have provided in the OpenMS issue I have to admit that I cannot come up with any answer to that. Only the first mass in the SPS mass list contains `isolation window offset` properties (similar to any other MSn precursor). Having a value of `-0.5` means that for some reason the RAW file reported `-1` as the width of the precursor isolation window. Sometimes `-1` is used as **no-value** by Thermo, however, it has not seen it being used in isolation window context.

Do you observe negative isolation margins for all spectra or it is only a few?

Which version of ThermoRawFileParser are you using? (Version 1.3.2 is fairly old, there has been a couple of updates to the way isolation window width is parsed in the later versions: see #152 for details, i.e. it might be fixed already)

Could you share an exemplary RAW file?

**Comment by radusuciu** [comment]
Hi, thank you for the quick response!

I observe negative isolation margins for all MS3 scans in this particular file - only on the first SPS mass as you pointed out. I have not yet tried other files. I can't share the particular raw file I've been working with, but I should be able to dig something up that was acquired within the same run and will share after confirming that it has the same issue. Do you have a preferred upload location?

I've tried 1.2.3, 1.3.1, 1.3.2, 1.4.0 and 1.4.2 and see it with all versions >= 1.3.1

Thanks!

**Comment by caetera** [comment]
I do not have any preferred upload provider, so anything that can do the job. 

Having an example would be very helpful since it does seem to be an issue only with some files - I have downloaded a couple of SPS files from PRIDE and they do not have any negative isolation margins after converting them to mzML and `IsobaricAnalyzer` processes them without any troubles.

**Comment by radusuciu** [comment]
May I email you a link to the file, and if so, is the email tagged in git commits in this repo fine? Unfortunately we did not have a HeLa or similar dataset acquired with the same settings, but I've gotten permission to share so long as it's not publicly available. Thanks!

I've also looked at a few SPS files from PRIDE and was not able to replicate the issue so it might be something specific to our methods.

**Comment by caetera** [comment]
Yes, you can send your link to vgоr (аt) bmb (dоt) sdu (dоt) dk

**Comment by radusuciu** [comment]
That solution sounds perfect!

I will test and report back.

**Comment by radusuciu** [comment]
Alright, I have converted the same file I shared with you with the pre-release and tested with an internal pipeline, sage, and the quantms pipeline. I did not perform a detailed comparison to ensure that the data did not change at all but everything executed without errors and the numbers look good.

Thank you again for working on this!

**Comment by caetera** [comment]
Released in version 1.4.3
