### ISSUE TITLE
Issue reading my file

### ISSUE THREAD

**Issue by agboken** [compomics/ThermoRawFileParser#169]
Hi
I tried using this app but I'm getting the following error:

```
Cannot run program
"C:\Users\kuagbo\resources\ThermoRawFileParser\ThermoRawFileParser.exe": CreateProcess error=2, The system cannot find the file specified
```

Please, where did I get it wrong?

**Comment by caetera** [comment]
Hi @agboken,

Thank you for using ThermoRawFileParser. Could you, please, provide more information on how you run the program?
Judging by the error message, it looks like your system cannot find or run the executable file. Is the path `C:\Users\kuagbo\resources\ThermoRawFileParser\ThermoRawFileParser.exe` correct? Is the execution restricted by antivirus software or similar?
