### ISSUE TITLE
Exclude Exception Data

### ISSUE THREAD

**Issue by corinnabrungs** [compomics/ThermoRawFileParser#171]
Hello,

I have a question regarding the exclude exception data function. I'm not sure if this is related to Thermo and their tagging of signals, but the removal only works for MS2 data. MS level >2 still includes those exception data. 

MS2 without exclude Exception data
![image](https://github.com/compomics/ThermoRawFileParser/assets/53823597/b17680ef-cb42-45d4-8ec0-408e9e1edee7)

MS2 with exclude exception data
![image](https://github.com/compomics/ThermoRawFileParser/assets/53823597/3ba2ac0d-a620-4600-a712-acce7a2cc4a7)

MS3 with exclude exception data
![image](https://github.com/compomics/ThermoRawFileParser/assets/53823597/acca8006-0975-45f2-a159-d857b187cff4)

**Comment by corinnabrungs** [comment]
Thanks for your quick reply. I thought it must be related to the tagging.

**Comment by caetera** [comment]
Closing. Please, reopen, if necessary.
