### ISSUE TITLE
Export Instrument Method name in Metadata output

### ISSUE THREAD

**Issue by baezaj** [compomics/ThermoRawFileParser#172]
Hi All,

I was hoping to extract the Instrument Method file name from the Sample Information section in a raw file.  It seems like this feature is supported. see image

![image](https://github.com/compomics/ThermoRawFileParser/assets/38925648/89b0f67b-a02d-4194-a7d1-5f558620c576)

However, when I look in the metadata file, the Instument Method file isn't listed. 

I am using v1.4.2 with the following arguments:
 "C:\Path\to\ThermoRawFileParser.exe" -i="C:\Path\to\RawFile.raw" -f=1 -m=1

**Comment by caetera** [comment]
Hi @baezaj,
thank you for using ThermoRawFileParser.
Output of the instrument method filename to metadata was added only in version 1.4.3.

**Comment by baezaj** [comment]
Thank you so much. that was an easy fix. I've been looking for this feature for quite some time, so I'm happy to see it here. 
Is there a way to output only the metadata file (not the mzML file)? Am also happy to submit a new issue.
Thanks

**Comment by caetera** [comment]
Yes. It is possible to specify output file format (`-f`,  `--format`) as  `none` (case insensitive) or `4`.

**Comment by baezaj** [comment]
Perfect. Thank you so much.
