### ISSUE TITLE
How to compile in Mono?

### ISSUE THREAD

**Issue by phlaaj** [compomics/ThermoRawFileParser#174]
Hi, thank you for this project, it will be a great help. I'm a noob, wondering if someone can share the commands to compile the project with Mono? I have Mono installed, but currently no .exe file to point it to. I'm working on macOS. Thank you for the help

**Comment by caetera** [comment]
Hi @phlaaj,

thank you for your interest in ThermoRawFileParser. If you want to use it - just download the latest release from the release page  and run it with mono - `mono ThermoRawFileParser.exe <all other command line arguments>`. If you prefer, there is a java-based GUI. I do not have much experience with Mac, you need to install `mono-complete` or `mono-develop` (i.e. SDK and runtime) if you encounter "assembly not found" errors.
> Click [here](https://github.com/compomics/ThermoRawFileParser/releases) to go to the release page 
> You can find the ThermoRawFileParserGUI [here](https://github.com/compomics/ThermoRawFileParserGUI).

If you would like to modify the code and compile, then you can use `msbuild` (installed with Mono SDK). Run `msbuild <path to ThermoRawFileParser.csproj>` to compile the project. If you planning for more advanced development having an IDE, such as `Rider` (cross-platform) is a plus.

**Comment by caetera** [comment]
Closing the issue. Please, reopen if necessary.
