### ISSUE TITLE
Wrong annotation for EThCD and ETciD with last Tune v4.0

### ISSUE THREAD

**Issue by rolivella** [compomics/ThermoRawFileParser#175]
Hello

I'm having an issue with the new Tune v4.0. After processing the raw files with the last TRFP version the CID part of ETciD is lost. For instance: 

```xml
<activation>
  <cvParam cvRef="MS" accession="MS:1000045" value="88.6927185058594" name="collision energy" unitAccession="UO:0000266" unitName="electronvolt" unitCvRef="UO" />
  <cvParam cvRef="MS" accession="MS:1000598" value="" name="electron transfer dissociation" />
</activation>

```

Another raw file but acquired with the old Tune v3.5 and the last TRFP version does not lose the CID part, has can be seen in this code: 

 ```xml
<activation>
    <cvParam cvRef="MS" accession="MS:1000045" value="100.179542541504" name="collision energy" unitAccession="UO:0000266" unitName="electronvolt" unitCvRef="UO" />
    <cvParam cvRef="MS" accession="MS:1000598" value="" name="electron transfer dissociation" />
    <cvParam cvRef="MS" accession="MS:1002680" value="35" name="supplemental collision energy" unitAccession="UO:0000266" unitName="electronvolt" unitCvRef="UO" />
    <cvParam cvRef="MS" accession="MS:1002679" value="" name="supplemental collision-induced dissociation" />
</activation>

 ```
Could you please check? Here the mzMLs and RAWs: https://www.dropbox.com/scl/fo/06bn1v1a92xmxri1nsa36/h?rlkey=aeebgjt2ua3iuxdl58vhux4j3&dl=0

**Comment by caetera** [comment]
Hi @rolivella,
Thank you for using TRFP. I can confirm the error. The reason for it is, however not clear. I can see that the parsing library (the Thermo one) indeed reports that the corresponding scans do not have supplemental activation, i.e. TRFP has nothing to do with it. I have access to another Eclipse running Tune 4.0.4084.22, I will try to get some EThcD runs from this instrument to check if the error can be reproduced.

**Comment by rolivella** [comment]
Hi @caetera thank you for taking care of this. Let me know if the error can be reproduced for EThcD. In that I case I will try to open an issue with the parsing library devs.

**Comment by caetera** [comment]
Hi @rolivella,
I can confirm the same problem with files acquired on a different Eclipse. I am afraid the error stems not even from the parsing libraries, but from the Tune itself. Scan filter strings lack the `sa` flag, which is set for supplementary activation (on Tune < 4). I am not sure if this change was made for a reason, and, if not, why it has not been spotted yet by others.

@jshofstahl @jesse-canterbury, @chambm, do you know anything about this issue?

**Comment by rolivella** [comment]
OK @caetera I'll also discuss this issue with my teammates and let you know.

**Comment by rolivella** [comment]
Hi again, we checked a RAW file acquired with Tune 4.0.4091 and it has all the information at the header, so it means that is not an issue from Thermo's side:

![309281807-b73a69a7-2381-4df0-94b7-a0cd25397921](https://github.com/compomics/ThermoRawFileParser/assets/1679820/d99bccfe-0835-4eb8-8e17-c9962c82f54c)

**Comment by caetera** [comment]
Here is the comparison of two scans from the scan filters (scan 37) for the files you have shared. 

Tune 3.5: `ITMS + c NSI r d sa Full ms2 395.1844@etd100.18 395.1844@hcd15.00 [100.0000-801.0000]`

Tune 4.0: `ITMS + c NSI r d Full ms2 487.2693@etd88.69 487.2693@cid35.00 [100.0000-985.0000]`

The difference is `sa` that was previously used for all scans with supplemental activation and, I assume, is the reason why the libraries cannot detect it anymore. I am not sure if Thermo just changed the format of their scans without any warning, or if it is a bug of some kind. I will try to contact Thermo about it.
On a side note, I can see that the latest version of MSConvert do not detect supplementary activation in Tune 4.x files as well.

**Comment by jesse-canterbury** [comment]
Hi all, we can see this is a bug on our side.  We should be able to get this fixed for Tune 4.2, which should be released some time in the vicinity of ASMS '24.  Thanks a lot for the report!

**Comment by caetera** [comment]
Thank you for the update @jesse-canterbury.

@rolivella As an immediate solution, I will need to change the code to allow parsing of the files with invalid scan headers and hope to come up with a beta soon.

**Comment by rolivella** [comment]
@caetera good, thank you very much!

**Comment by caetera** [comment]
Hi @rolivella,
I have implemented a fix for the missing supplementary activation error. You can download and test the next beta version using this link: https://syddanskuni-my.sharepoint.com/:u:/g/personal/vgor_bmb_sdu_dk/EUq2DvQ3I_hEvf-N2_I3weUBCKeiRVeJNKv7sX0mmt2C7g?e=kRseht

**Comment by caetera** [comment]
The biocontainer repo will be updated only after the release, i.e. it will take some time more before it happens.
