### ISSUE TITLE
mzML file works with search engines but not with quantitation tools

### ISSUE THREAD

**Issue by foellmelanie** [compomics/ThermoRawFileParser#20]
Hi, 
I was running the thermo converter on usegalaxy.eu on several raw files to convert them to mzML files. The mzML files were compatible with search engines but not with moFF version 1.2.1 (error: could not find obo files). Featurefindermultiplex did not throw any error but did not quantify any feature either. The mzML files obtained with msconverter give results with moff and featurefindermultiplex.  

This is one of the raw files I tried to convert: 
https://galaxy.uni-freiburg.de/datasets/0b3e8078f6f876c0/display?to_ext=thermo.raw
The commandline was:
```
ThermoRawFileParser.sh -i=input.raw -o=./ -f=1 --metadata=1
```
ping @ypriverol

**Comment by ypriverol** [comment]
I have been testing the file and the number of MS1 is 8249. Can you provide me the mzML that you are getting with Galaxy.

**Comment by foellmelanie** [comment]
Hi @ypriverol, 

thanks a lot for checking the file! This is the mzML output from Galaxy:
https://galaxy.uni-freiburg.de/datasets/7ed056308214d5ba/display?to_ext=mzml

**Comment by nielshulstaert** [comment]
Hi Melanie,

I think it has to do with the controlled vocabulary entries in the cvList element; pymlML has problems with the owl format. I've changed the URLs to the obo format like msconverter is doing, I still need to test it with moff. I'm adding zlib compression for the binary data as well in the mean while, I'll let you know when the testing is done.

Best regards,

Niels

**Comment by ypriverol** [comment]
I'm testing with OpenMS and looks like the error is related with profile/centroid of MS1. The current tool export the profile MS1 and the OpenMS expect everything in Centroid.

**Comment by nielshulstaert** [comment]
Hi Melanie,

I've pushed a new version that should fix the obo error in pymzML. Could you test it let me know? 

Best regards,

Niels

**Comment by ypriverol** [comment]
@nielshulstaert This will not Solve the error that @foellmelanie reported. @foellmelanie is using moff and OpenMS. The problem that they have is with profile data. We should test some Quant in our side before testing by @foellmelanie .

**Comment by ypriverol** [comment]
I have tested the tool with OPenMS and it works fine !!!
