### ISSUE TITLE
I have try some examples and they don't work 

### ISSUE THREAD

**Issue by ypriverol** [compomics/ThermoRawFileParser#3]
I have tried some examples and they don't work. Here one of them https://www.ebi.ac.uk/pride/data/archive/2018/04/PXD009286/OTV_1801_007.raw

**Comment by nielshulstaert** [comment]
Hi Yasset,
This happened because the scan centroid streams are empty. Now it takes the segmented scan peaks instead in that case. I tried that RAW file with MSConvert and the results are the same now.

Best regards,

Niels
