### ISSUE TITLE
Performance Evaluation

### ISSUE THREAD

**Issue by yafeng** [compomics/ThermoRawFileParser#31]
Hi, I looked into a bit more about different raw file readers. I came across one [paper](https://www.ncbi.nlm.nih.gov/pubmed/26499134) published in Anal. Chem. 2015. 
**Extracting Accurate Precursor Information for Tandem Mass Spectra by RawConverter.**

There they have compared their tool RawConverter with ProteoWizard, and it seems RawConverter does better job than ProteoWizard.

I am wondering if you have done similar evaluation on ThermoRawFileParser.

**Comment by ypriverol** [comment]
Here, we have the comparison https://github.com/ypriverol/ThermoRawParser-paper between both tools.

**Comment by yafeng** [comment]
@ypriverol thanks!  I see there are many plots, but it is kind of difficult to interpret without additional information. are you planing to submit the paper? I can wait until the paper is online.

**Comment by ypriverol** [comment]
Here the link of the paper @yafeng https://www.biorxiv.org/content/10.1101/622852v1

**Comment by yafeng** [comment]
@ypriverol Thanks! I will spread the news on social media.
