### ISSUE TITLE
precursor mass for the MS3 spectra are missing

### ISSUE THREAD

**Issue by yafeng** [compomics/ThermoRawFileParser#35]
Hi, 
I encountered this problem when using ThermoRawFileParser to convert MS RAW file containing MS3 quantification. Example raw files can be downloaded from 
http://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD005953

It results an error later in IsobaricAnalyzer which tries to find precursor mass for MS3 spectra. 
ProteoWizard converted mzML files contain precursor mass for MS3 spectra. 

I discussed the issue with developer for IsobaricAnalyzer on github. They helped me point out where the problem is.
https://github.com/OpenMS/OpenMS/pull/2595#issuecomment-487206888

**Comment by ypriverol** [comment]
@nielshulstaert I will take care of this issue.

**Comment by yafeng** [comment]
@ypriverol Thanks for the quick response! I can't run docker here. 
You can test it by
```
conda install -c bioconda openms
IsobaricAnalyzer  -type tmt10plex -in example.mzML -out "example.mzML.consensusXML" -extraction
:select_activation "" -extraction:reporter_mass_shift 0.002 -extraction:min_precursor_intensity 1.0 -extr
action:keep_unannotated_precursor true -quantification:isotope_correction true
```
If it runs without error, it should be OK.

**Comment by ypriverol** [comment]
Ok I will do it!! Any of the files of that project are fine for the test

**Comment by yafeng** [comment]
Yes, you can choose any file from the project to test.

**Comment by ypriverol** [comment]
I have fixed the error @yafeng . We will wait for @nielshulstaert to review the PR #37

**Comment by nielshulstaert** [comment]
Hi @ypriverol and @yafeng I'm looking into this. I want to make sure that the MS3 precursor element is populated correctly.

**Comment by ypriverol** [comment]
@yafeng we have updated the library, here the new release  https://github.com/compomics/ThermoRawFileParser/releases/tag/v1.1.4
