### ISSUE TITLE
Consider changing the project name

### ISSUE THREAD

**Issue by prvst** [compomics/ThermoRawFileParser#36]
I suggest to the team to consider changing the name of this project. Companies often relies on aggressive legal terms prohibiting third-party and/or external personal to use their brand names on unrelated products. Moby (a.k.a. Docker) did a very similar thing some time ago demanding that people stop creating new software / products by adding the word Docker to them, this was one of the reasons we had to re brand the BioDocker project to BioContainers. By adding the word "Thermo" as a prefix, it also may pass the idea that this is some kind of oficial project made by Thermo Fischer. It is better to address this issue before the publication is out than having to change it later because a cease and desist.

**Comment by ypriverol** [comment]
@prvst so far with Thermo @lnnrt team never had an issue. See here another previous parser https://www.ncbi.nlm.nih.gov/pubmed/21714566

**Comment by prvst** [comment]
Yes, and the same thing can be said about the ThermoFinigan converter, but
that doesn't mean that the company will not start enforcing their trademark
tomorrow. The word Thermo is trademarked, you will always be at risk to
have it changed.
