### ISSUE TITLE
Dummy file produced in case of error

### ISSUE THREAD

**Issue by timosachsenberg** [compomics/ThermoRawFileParser#41]
Hi,
After conversion of:  https://github.com/HegemanLab/small-thermo-raw-file-examples/blob/master/ginkgotoxin-ms-switching.raw to idexed mzML
I get an:
IndexedMzMLDecoder::domParseIndexedEnd Error: expected only 'spectrum' or 'chromatogram' below indexList but found instead 'dummy' when reading in OpenMS.

**Comment by timosachsenberg** [comment]
ok this is probably related to an error on my side (specified an output file instead of the output directory).
Should not generate an empty file though...

**Comment by ypriverol** [comment]
What do you think is better for you, to have an option that you can specify an output file name. ?

**Comment by timosachsenberg** [comment]
Yes, this would be better for us. I will work around that for now
