### ISSUE TITLE
We should have an option for one file output

### ISSUE THREAD

**Issue by ypriverol** [compomics/ThermoRawFileParser#42]
@Timo has suggested in the following issue https://github.com/compomics/ThermoRawFileParser/issues/41#event-2329730097 that would be great to have `-input_file`  and `output_file` design for tools that needs one input, one output instead of the folder approach.

**Comment by timosachsenberg** [comment]
Yes, this would be great for workflow based approaches. The latter guarantees that exactly one file is generated.

**Comment by ypriverol** [comment]
The following PR https://github.com/compomics/ThermoRawFileParser/pull/44 provides a new parameter `-b` where the user can provide the name of the file path to output the data.

**Comment by ypriverol** [comment]
@timosachsenberg we have a new release with output_file included https://github.com/compomics/ThermoRawFileParser/releases/tag/v1.1.4
