### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by rmflight** [compomics/ThermoRawFileParser#43]
Or if there was a way to set up CI for this repo, then there could be a release for each pull request merged into master.

Or if there was more instructions on how to compile the project on Windows / Linux (I personally have no experience compiling .net on either platform).

Sorry, I'm just really anxious to compare the output of the profile mode to what I get from MSConvert, b/c I'd be really happy to be able to have my entire workflow on Linux.

**Comment by ypriverol** [comment]
@rmflight We will implement a CI and do as soon as possible a release. We are now fixing multiple issues. 

Another thing, when you finish the benchmark can you make then available if is possible. ?

**Comment by rmflight** [comment]
Sure, I can definitely make any benchmarking analysis I do available.

**Comment by ypriverol** [comment]
@rmflight we just release a new version: https://github.com/compomics/ThermoRawFileParser/releases/tag/v1.1.4
