### ISSUE TITLE
Problems with locale

### ISSUE THREAD

**Issue by timosachsenberg** [compomics/ThermoRawFileParser#45]
http://cdash.openms.de/testDetails.php?test=56856527&build=312104
On windows a number 123.456 gets converted to 123456. potentially a problem with locale.
The ! Indicates the mismatch between test file an reference created on linux

**Comment by timosachsenberg** [comment]
Offending lines:			(tab_width = 8, first_column = 1)

in1:  C:\jenkins\ws\openms_pr_ci\979a8a2f\build\src\tests\topp\ginkgotoxin-ms-switching_out_tmp.mzML   (line: 72, position/column: 64/65)
              <cvParam cvRef="MS" accession="MS:1000927" value="!
                                                                170945" name="ion injection time" unitAccession="UO:0000028" unitName="millisecond" unitCvRef="UO" />

in2:  C:\jenkins\ws\openms_pr_ci\979a8a2f\source\src\tests\topp\THIRDPARTY\ginkgotoxin-ms-switching_out.mzML   (line: 72, position/column: 64/65)
              <cvParam cvRef="MS" accession="MS:1000927" value="!
                                                                170.945" name="ion injection time" unitAccession="UO:0000028" unitName="millisecond" unitCvRef="UO" />

**Comment by ypriverol** [comment]
@timosachsenberg can you provide the file example for testing?

**Comment by timosachsenberg** [comment]
HI. https://github.com/OpenMS/OpenMS/blob/a02db7a7e2b6b8dd18fdd2c0a52907fc36ded02c/src/tests/topp/THIRDPARTY/ginkgotoxin-ms-switching.raw
@jpfeuffer do you know if we run german windows on the test machine?

**Comment by jpfeuffer** [comment]
Yes the region and language settings are set to German.

**Comment by ypriverol** [comment]
Looks like a problem in the Thermo API.

**Comment by nielshulstaert** [comment]
Hi @timosachsenberg I notice the same problem on machine with belgian locale. I'll try to fix it and get back to you.

**Comment by ypriverol** [comment]
@nielshulstaert I have check the error yesterday. In this line https://github.com/compomics/ThermoRawFileParser/blob/master/Writer/MzMlSpectrumWriter.cs#L837 we capture the Injection time as String from thermo api. Then, probably the error is in thermo API side? I have contacted Jim about this. What do you think?

**Comment by nielshulstaert** [comment]
I think the problem is on our side, the String from the thermo api is depending on the locale (comma or point as decimal separator) so I should be able to fix it.

**Comment by nielshulstaert** [comment]
Hi @timosachsenberg I released a new version (1.1.5) can you test it? Thanks for trying out the library.

**Comment by timosachsenberg** [comment]
will do. Thanks for the quick fixes!

**Comment by timosachsenberg** [comment]
@nielshulstaert Hi we just encountered a similar error (see the linked issue)

Depending on the locale we either get:
<userParam name="[Thermo Trailer Extra]Monoisotopic M/Z:" type="xsd:float" value="1112,523" />
or:
<userParam name="[Thermo Trailer Extra]Monoisotopic M/Z:" type="xsd:float" value="1112.523" />

It would be great if you could take a look at that. Hopefully just a small fix as before.

**Comment by caetera** [comment]
Hi @nielshulstaert, I have added few changes to make InvariantCulture a default one for everything, that should solve this kind of problems once and for all. With this it should not be necessary to set it for every export. Please, check latest commit on the hackathon branch.
I don't have access to PCs with many different locales and thus cannot test it much. Can you check if it solves your problem @timosachsenberg?
