### ISSUE TITLE
Precursor Intensity has a value of 0??

### ISSUE THREAD

**Issue by rmflight** [compomics/ThermoRawFileParser#47]
When I read in the file using the `xcms` R package, the `msnPrecursorIntensity` has a value of 0. When comparing my two `mzML` files, I see these differences in the `precursorList`:

## msconvert
    <selectedIonList count="1">
                <selectedIon>
                  <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="734.569152832031" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                  <cvParam cvRef="MS" accession="MS:1000041" name="charge state" value="1"/>
                  <cvParam cvRef="MS" accession="MS:1000042" name="peak intensity" value="1.7700104e07" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"/>
    </selectedIon>

## ThermoRawFileParser
    <selectedIonList count="1">
                <selectedIon>
                  <cvParam cvRef="MS" accession="MS:1000744" value="734.569152832031" name="selected ion m/z" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />
                  <cvParam cvRef="MS" accession="MS:1000041" value="1" name="charge state" />
                </selectedIon>
    </selectedIonList>

So it looks like the peak intensity for the selectedIon is missing from the ThermoRawFileParser.

Now, I don't do anything with MS2 scans in my work, and I'm processing my data in a very particular way, so I'm not sure *how important* this difference actually is, and whether any other software will care, but it is a difference I see, so I thought I should point it out.

These are both profile data conversions, btw. But I still don't see a value for the `peak intensity` if I generate centroided data either.

`v117_snapshot`

**Comment by nielshulstaert** [comment]
Hi @rmflight indeed the precursor intensity isn't there yet, neither in the MGF nor the mzML output. I've figured out how to calculate it for both centroid and profile data but I still need to test it. Also it will slow the conversion down so I might add it as (yet another) flag in a future release. It's also not clear to me whether this value is used by search engines for example.

**Comment by timosachsenberg** [comment]
I use the precursor intensity in one of my tools but have to admit that it usually doesn't help too much in improving results.

**Comment by hbarsnes** [comment]
@nielshulstaert Any update on getting the precursor intensity included in the mgf and mzml outputs?

**Comment by hbarsnes** [comment]
Please see https://github.com/compomics/ThermoRawFileParser/issues/78 for an update on this issue.

**Comment by caetera** [comment]
Precursor intensity has been added in version 1.4.0, thus, I will close the issue.
