### ISSUE TITLE
MS max charge in meta json

### ISSUE THREAD

**Issue by UKQIDA** [compomics/ThermoRawFileParser#49]
Hi Niels and Yasset @nielshulstaert @ypriverol 
When I convert a thermo raw file to mgf, the result meta.json file contains {"accession":"PRIDE:0000473","cvLabel":"PRIDE","name":"MS max charge","value":"2"}.
However, the charge values in mgf contains 3+ and 4+. Is there anything that I get it wrong or this is a real issue?
Thanks
Da
Below is part of mgf file: 
BEGIN IONS
TITLE=controllerType=0 controllerNumber=1 scan=4
SCANS=4
RTINSECONDS=0.555008863
PEPMASS=367.069610595703
CHARGE=3+
102.9147415 587.6849365234
103.0570450 1049.8944091797
111.1171875 1026.8439941406
120.2493973 612.2634277344
124.1555634 882.5004882813
135.8387756 703.7473754883

**Comment by nielshulstaert** [comment]
Hi Da, indeed there's a bug in the code. It should be fixed in the latest release (v1.1.7). Thanks for pointing this out!
