### ISSUE TITLE
zlib and X!Tandem

### ISSUE THREAD

**Issue by Arthfael** [compomics/ThermoRawFileParser#51]
I am trying to search some Thermo Raw files using X!Tandem in OpenMS (Knime version). For this, I need to convert the files to mzML. I tried using ThermoRawFileParser:
`"...ThermoRawFileParser.exe" -i=".../MyThermoRawFile.raw" -b=".../MyOutputFile.mzML\" -f=1`
However, the XTandemAdapter node then gives me the following error:
_"Fatal error: unsupported CODEC used for mzML peak data (CODEC type=zlib compression)"_

I also tried -f=2 but whether the data is indexed or not does not seem to make a difference (incidentally, which would you recommend by default?)

Is there a way to use a different conversion CODEC than zlib is used? Adding the -p argument makes as expected for a much larger mzML file, but I get instead this error from XTandemAdapter:
_"Error: Profile data provided but centroided MS2 spectra expected. To enforce processing of the data set the 'force' flag."_ I could try the recommendation, but of course this would massively inflate the data size.

**Comment by nielshulstaert** [comment]
Hi,

I'll add a flag next week that disables the zlib compression. I'll keep you posted. 

Best regards,

Niels

**Comment by Arthfael** [comment]
Thank you so much for your prompt answer (I love how reactive people can be
in this community!)


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_-8565490318716961285_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by nielshulstaert** [comment]
Thank you for trying out the parser! I've released a new version (1.1.9) with a `-z` flag that disables the zlib compression. Could you give it a go?

**Comment by Arthfael** [comment]
Hi Niels,

Sorry for the delay in answering, I did not find the time to test the new
version until now. So far so good, I have successfully converted 5
different Raw files to mzML with zlib off and am now able to feed them into
X!Tandem on OpenMS without the previous error. Thanks a lot!
Best,

Armel
