### ISSUE TITLE
Could I convert mzML file  to mgf file?

### ISSUE THREAD

**Issue by cclinglings** [compomics/ThermoRawFileParser#52]
I've got a public dataset, which is mzML format. I want to use mascot search engine, whose input must be mgf file. Could I convert mzML file  to mgf file? Thank you!

**Comment by hbarsnes** [comment]
ThermoRawFileParser only supports the conversion of Thermo raw files. To convert mzML files you need to rely on other tools. See for example [ProteoWizard](http://proteowizard.sourceforge.net).

**Comment by cclinglings** [comment]
ok. I need a tool could work at Linux, so ProteoWizard msconvert is not suitable for me.  thank you.

**Comment by caetera** [comment]
Since you don't need vendor format support, native Linux version of Proteowizard should work for you

**Comment by cclinglings** [comment]
Yes, it works. Thank you!
