### ISSUE TITLE
Problem in Galaxy workflow managing multiple raw files with ThermoRawFileParser

### ISSUE THREAD

**Issue by CarlosHorro** [compomics/ThermoRawFileParser#54]
Hi all,

Here at Barsnes' group we are using a Galaxy workflow which includes in its first steps ThermoRawFileParser.
When we try to convert multiple raw files, it seems that the tool accepts just one raw file (per job), which conflicts with the workflow (one job per step, even using multiple files per job). Would it be possible to add one option to ThermoRawFileParser like "-d"( input directory), so the tool converts all raw files available in one folder in just one step? or maybe the possibility to introduce a list of files separated by commas in the -i/--input option? 
It would facilitate a lot our work...

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
May I contribute to ThermoRawFileParser trying to implement this functionality?

**Comment by bgruening** [comment]
@CarlosHorro of course! See here: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/ThermoRawFileParser

**Comment by CarlosHorro** [comment]
Great, thanks! :-)
Well, the Galaxy tool does not seem very complicated :-)  But I suppose I will have to work firstly on implementing the folder as input functionality here...

**Comment by CarlosHorro** [comment]
I created the PR, although I'm not sure about if here changes are directly merged or firstly reviewed (as I did...)

**Comment by CarlosHorro** [comment]
#55

**Comment by nielshulstaert** [comment]
Hi @CarlosHorro my apologies for the late reply, I was on holidays for the last couple of weeks. I've merged your PR into the revision branch that I'm working on. I'm adding some other functionality and will release a new version this week. Thanks for contributing and I'll keep you posted!

**Comment by CarlosHorro** [comment]
> Hi @CarlosHorro my apologies for the late reply, I was on holidays for the last couple of weeks. I've merged your PR into the revision branch that I'm working on. I'm adding some other functionality and will release a new version this week. Thanks for contributing and I'll keep you posted!

Thank you very much, great news! :-)

**Comment by nielshulstaert** [comment]
Hi @caetera I've released a [new version](https://github.com/compomics/ThermoRawFileParser/releases/tag/v1.1.10-beta) with your pull request. Could you test it? I'll update the README file and merge with the master afterwards.

**Comment by caetera** [comment]
Hi Niels,
you probably wanted to mark @CarlosHorro

**Comment by CarlosHorro** [comment]
> Hi Niels,
> you probably wanted to mark @CarlosHorro

If it was referred to me, of course I will test it :-)

**Comment by CarlosHorro** [comment]
Ok, I've tested all options apart from the ones related to S3 and everything seems to work :-)
