### ISSUE TITLE
Directory parsing error

### ISSUE THREAD

**Issue by adecourcy** [compomics/ThermoRawFileParser#58]
Hi,

I'm trying to use this on a Windows 10 machine and attempting to provide the absolute path to an input and output directory. However, when I do so I'm getting an invalid directory error.

For reference, here is the command I am using:

`& "D:\Documents\Research Projects\GUI\ThermoRawFileParser\bin\x64\Debug\ThermoRawFileParser.exe" -d="D:\Documents\Research Projects\GUI\data\raw\"`

and the error I'm getting:

`-d, --input_directory: specify a valid input directory`

The directory provided is a valid directory. I'm guessing this has something to do with the fact that I'm providing an absolute path, or a path that contains a space possibly? Is there a way to work around this? I would like to be able to provide absolute paths, as well as paths with spaces if possible.

Thanks.

**Comment by nielshulstaert** [comment]
Hi thanks for trying out the parser. Indeed there seems to be an issue with spaces in the path on Windows. It works with me after removing the last backward slash (`d="D:\Documents\Research Projects\GUI\data\raw`). For paths without spaces, the trailing slash doesn't make a difference. 

Let me know if that works for you and I'll fix this in a next release.

**Comment by nielshulstaert** [comment]
After some debugging, it seems like the backslash quote combination `\"` is seen as an escaped quote so it will mess up your arguments if you use any other ones after it (like `-f=0`). The easiest solution is to avoid this. 

Thanks for letting this know, I'll add it as remark in the help output for the `--input directory` option.

**Comment by adecourcy** [comment]
That worked for me! Thank you very much for your help on this!
