### ISSUE TITLE
MacOS ThermoRawFileParser

### ISSUE THREAD

**Issue by Adafede** [compomics/ThermoRawFileParser#59]
Hi,

Just to inform you the GUI is not working on MacOS Catalina because of Mono ("Error 2 Mono"), but command line is working!

**Comment by hbarsnes** [comment]
Thanks for letting us know. It used to work on MacOS before though. Given that the command line works I assume you have Mono installed, so what is the command line you are able to run?

**Comment by hbarsnes** [comment]
I've uploaded a debug version of the GUI that you can test here: http://vedlegg.uib.no/?id=e0c0c54f46042bd0af1860eb67800c2e. The only change is that it prints the command line before executing the parser. That way you can compare it to the one you run directly from the command line.

**Comment by Adafede** [comment]
Wow, super fast!

Just tested your debug...

Here is what I input as command line: 

> mono ThermoRawFileParser.exe -i=/users/rutza/Downloads/Test.raw -b=/users/rutza/Downloads/test.mzml -f=1 -g -m=0

(working)

Here is what the debug GUI gives me:
<img width="631" alt="Capture d’écran 2019-10-24 à 14 40 57" src="https://user-images.githubusercontent.com/44283913/67486447-54232100-f66c-11e9-8e73-ccc565413175.png">

(not working)

Thank you very much!

**Comment by Adafede** [comment]
```
Adriano:ThermoRawFileParserGUI-1.2.0-debug rutza$ mono /Users/rutza/Downloads/ThermoRawFileParserGUI-1.2.0-debug/resources/ThermoRawFileParser/ThermoRawFileParser.exe -i=/Users/rutza/Downloads/Test.raw -o=/Users/rutza/Downloads -f=0 -e
2019-10-24 14:47:42 Started parsing /Users/rutza/Downloads/Test.raw
2019-10-24 14:47:42 Processing 4784 scans
10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
2019-10-24 14:47:43 Finished parsing /Users/rutza/Downloads/Test.raw

```
Works

**Comment by hbarsnes** [comment]
Ok, so then the problem seems to be that mono is not in your general path. I'm not a Mac/Linux user myself, but there seems to be other Mac users having similar issues with Mono. See for example: https://stackoverflow.com/questions/32542535/how-to-install-mono-on-macos-so-mono-works-in-terminal. Hopefully some of those tips will solve the issue?

**Comment by Adafede** [comment]
I think the problem is in your config files looking where to find mono...I'm not sure I can modify it.

Just quickly ran which is mono:

> /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono

**Comment by hbarsnes** [comment]
> I think the problem is in your config files looking where to find mono...I'm not sure I can modify it.

There are no config files for the GUI. It simply runs the command line displayed in the debug version. I will try to ask around for help from other Mac/Linux users and get back to you.

**Comment by hbarsnes** [comment]
Here's a new debug version that sets the executable path to the same path as the GUI jar file before running the mono command: http://vedlegg.uib.no/?id=f1a82a1f8c59356afb0833289e5974db. Can you see if that makes a difference?

**Comment by hbarsnes** [comment]
With the help of @CarlosHorro we have now released a new version that should solve the issue on MacOSX El Capitan (10.11) and later: http://genesis.ugent.be/maven2/no/uib/thermo-raw-file-parser-gui/ThermoRawFileParserGUI/1.2.1/ThermoRawFileParserGUI-1.2.1.zip.

Please give it a go and let us know if it works for you as well. If not, we'll reopen the issue.

**Comment by Adafede** [comment]
Perfectly working, thanks a lot!
