### ISSUE TITLE
Add procps package to docker image for Nextflow tracing support

### ISSUE THREAD

**Issue by courcelm** [compomics/ThermoRawFileParser#62]
The current Docker image is missing ps and therefore can't run with Nextflow tracing.
```
Nextflow error:
Command 'ps' required by nextflow to collect task metrics cannot be found

# Add missing dependencies for Nextflow
RUN apt-get update -qq && \
    apt-get install -y \
            procps && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by nielshulstaert** [comment]
Hi thanks for the suggestion. @ypriverol could you have a look at this?

**Comment by RalfG** [comment]
@courcelm, `ps` should be available in the bioconda/biocontainers docker image. You can try with
```sh
docker run --rm -it quay.io/biocontainers/thermorawfileparser:1.3.3--ha8f3691_1 ps
```

**Comment by RalfG** [comment]
@ypriverol, could/should `procps` be added to the Dockerfile(s) in this repo, or not?

This somewhat relates to my question in #113

**Comment by RalfG** [comment]
Closing, as Dockerfiles in this repo will be removed in favor of biocontainers image (see #113).
