### ISSUE TITLE
question about license

### ISSUE THREAD

**Issue by lucacozzuto** [compomics/ThermoRawFileParser#63]
Dear developers,
I have a question about the possibility of redistributing code from Termofisher (both executable and dll). I'm just wondering if this is ok, or not.

Many thanks,

Luca

**Comment by rolivella** [comment]
Hi @nielshulstaert , we @lucacozzuto and I are working on implement the ThermoRawFileParser into the QCloud master pipeline, for this we need to clarify this license question. AFAIK the point is: 

The license at https://github.com/compomics/ThermoRawFileParser/blob/master/LICENSE only applies to the DLL files from Thermo, not to all your code. Is this the case? Thank you!

**Comment by nielshulstaert** [comment]
Hi this license indeed only applies to the Thermo DLL files. @ypriverol do I rename this file and add an apache2 or other license?

**Comment by nielshulstaert** [comment]
Apache license added and renamed thermo license to THERMO_LICENSE

**Comment by lucacozzuto** [comment]
Hi @nielshulstaert, my question was not about adding a new kind of license but if you (and other people like me) are authorised to redistribute the dll code inside our own github repositories. Thanks!
