### ISSUE TITLE
mzXML?

### ISSUE THREAD

**Issue by poofcakes** [compomics/ThermoRawFileParser#64]
Are there any plans to support mzXML output?

**Comment by caetera** [comment]
Hi, @poofcakes, is there a particular use case where mzML cannot be used instead of mzXML? I mean, mzXML seems to be deprecated in favor of mzML. Most of the tools that I am aware of either support both format or more dead than alive. Implementing proper mzXML output is rather labor-intensive task.

**Comment by poofcakes** [comment]
I see. I was asking because It's what our diagnostic pipeline has used for many years. I tried to use mzML just to see if it would work, but it seems to bug out somewhere. Still looking into why. If I'm the only one with a need for it, then I understand it's not worth it. 🙂

**Comment by edeutsch** [comment]
As a voice from the group that originally came up with mzXML, I heartily support switching to mzML, and not prolonging the deprecated mzXML. We have! Note also that once you have converted from RAW to mzML (presumably using Linux+mono), it is easy to convert the mzML to mzXML using msconvert (under Linux). This is an extra step, of course, but perhaps not unreasonable for a deprecated format.
