### ISSUE TITLE
Possible bug: userParam float value written out with comma on Windows

### ISSUE THREAD

**Issue by enetz** [compomics/ThermoRawFileParser#65]
There is a line that the parser writes out for each MS2 spectrum I think, it looks like this when a file is converted on german Windows 8.1:
<userParam name="[Thermo Trailer Extra]Monoisotopic M/Z:" type="xsd:float" value="1112,523" />

and this is the same file converted on Linux:
<userParam name="[Thermo Trailer Extra]Monoisotopic M/Z:" type="xsd:float" value="1112.523" />

On Windows a comma is used for the float number.
This case might be similar to #45  and a problem with locale, it was discovered on a german Windows installation.

Tested with ThermoRawFileParser v1.1.11 and  ThermoRawFileParserGUI v1.2.1

**Comment by caetera** [comment]
Hi, @enetz, could you build the latest version from **eubic2020hackathon** branch and test if it will resolve the issue? I can provide binaries, if necessary.

**Comment by enetz** [comment]
@caetera binaries would be helpful, as I have never built the ThermoRawFileParser before and probabaly won't be able to set it up quickly

**Comment by caetera** [comment]
You can download the binaries from https://filesender.deic.dk/?s=download&token=34ad69a5-76ab-2ea0-51c2-540e97231c04

**Comment by enetz** [comment]
@caetera thanks, I will test this on Windows and Linux today.

**Comment by enetz** [comment]
@caetera Thanks! This works on german Windows 8.1 and Linux.

@nielshulstaert @ypriverol 
Would it be possible to backport this commit 
6b6f0266d59eb0733b0f01d747086f10e09b40d7
to master and make a new release?

We are preparing the release of OpenMS 2.5 and this bug makes the ThermoRawFileParser unusable in OpenMS pipelines on german (and probably a few other) Windows versions.

**Comment by timosachsenberg** [comment]
Hi @caetera @nielshulstaert ,
I saw this issue got closed and would like to know if the commit will be ported 
to master and released? In it's current state it is broken for us. 
Best,
Timo

**Comment by caetera** [comment]
Hi Timo, 
Niels promised to merge all to master and release it very soon.

**Comment by timosachsenberg** [comment]
Hi, thanks for the quick fixes - any chance to get a new release?
