### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by timosachsenberg** [compomics/ThermoRawFileParser#67]
Hi @nielshulstaert thanks a ton for creating the new release.
There seems to be a small typo:
Tag is:  v1.2.0  a6f8e37
But the release title is v1.1.2 on the release page (which would indicate an old release)
Best,
Timo

**Comment by nielshulstaert** [comment]
Thanks Timo, I fixed it. I'll update the readme file with the new features tomorrow.
