### ISSUE TITLE
TRFP 1.2.0 fails on test data

### ISSUE THREAD

**Issue by timosachsenberg** [compomics/ThermoRawFileParser#68]
D:\TRFP1.2.0>ThermoRawFileParser.exe -i "ginkgotoxin-ms-switching.raw" -b test.mzML
now fails with:
-o, --output: specify a valid output directory

**Comment by nielshulstaert** [comment]
Hi Timo, I did some refactoring of the argument parsing and this slipped through, thanks for letting me know!
