### ISSUE TITLE
[FeatureRequest] Adding progress bar

### ISSUE THREAD

**Issue by tivdnbos** [compomics/ThermoRawFileParser#72]
When using ThermoRawFileParserGUI, it would be nice to show somewhere how many raw files already have been parsed. When parsing many raw files at once, this would make it easier to estimate how long it will take. This will also be interesting for the command-line version, but I'm not sure if that already exists or not.

**Comment by hbarsnes** [comment]
Should not be too difficult to add in ThermoRawFileParserGUI. I will try to look into it later this week and let you know.

**Comment by caetera** [comment]
Command-line version reports progress of each individual file.

**Comment by hbarsnes** [comment]
Just deployed ThermoRawFileParser 1.3.0 with progress display. Both for the number of files converted and for each individual file.

**Comment by tivdnbos** [comment]
Thanks Harald!
