### ISSUE TITLE
Produced mzML files cannot be handled by R's mzR::openMSfile function

### ISSUE THREAD

**Issue by higsch** [compomics/ThermoRawFileParser#73]
I produced mzML files from Thermo raw files using the docker version like that:
```
docker run -v /data:/data -i -t thermorawparser mono /src/bin/x64/Debug/ThermoRawFileParser.exe -d=/data/raw -o=/data/mzml/ -f=1 -m=1 -e -p
```
The raw files were SPS-MS3 files from an Orbitrap Lumos instrument. It all worked fine, I could run a MSGFplus search and detect TMT quantifications with OpenMS IsobaricAnalyzer.

However, when I wanted to open a spectrum in R with
```
spectra_list <- mzR::openMSfile(filename = mzml_file)
```
I got this error:
```
Error: Can not open file file.mzML! Original error was: Error in pwizModule$open(filename): c++ exception (unknown reason)
```
I first thought there is something going wrong with `Rcpp`, but then I realised that when I convert the files with `msconvert`, everything is fine again.

So does `ThermoRawFileParser` modify the files in a way that I cannot open them with `mzR::openMSfile` any more? I also tried switching on/off the `zlib` compression and peak picking, but that didn't help.

**Comment by caetera** [comment]
Hi Matthias,
Could you share some representative example of a file you used?

**Comment by higsch** [comment]
Unfortunately, it's unpublished collaborator's data, but should be published in a couple of days, then I can link them.

**Comment by caetera** [comment]
As a quick check could you please, see if both mzML files (the one from ThermoRawFileParser and the one from ProteoWizard) pass validation against mzML scheme? You can use, for example, XMLValidator from OpenMS - https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/UTILS_XMLValidator.html

**Comment by higsch** [comment]
I used XMLValidator version 2.3.0, no schema file.

For the ThermoRawFileParser I get:
```
Validation error in file '20200402_5v5_F3.mzML' line 68 column 156: value '20200402_5v5_F3' is invalid NCName
```

For msConvert I get numerous error lines like this one:
```
Validation error in file '20200402_5v5_F3.mzML' line 5864994 column 53: attribute 'name' is not declared for element 'userParam'
Validation error in file '20200402_5v5_F3.mzML' line 5864994 column 53: attribute 'value' is not declared for element 'userParam'
Validation error in file '20200402_5v5_F3.mzML' line 5865009 column 25: element 'userParam' is not allowed for content model '(isolationWindow?,selectedIonList?,activation)'
```

**Comment by caetera** [comment]
Well, the error does not say much. The validation error should be solved by renaming the file so that the first character is letter, for example "a20200402_5v5_F3", however, not sure if it will solve the initial problem.
If not, the best option is to wait until the data become public.

**Comment by higsch** [comment]
So finally, the dataset is out. https://www.ebi.ac.uk/pride/archive/projects/PXD018357. The issue happens basically with all the `20200317_KKL_CoV2_24h_5v5_F*.raw` files.

**Comment by caetera** [comment]
Good. I will try to check it ASAP (it will, likely, take some time), help from other people is appreciated.

**Comment by caetera** [comment]
Hi @higsch 

could you check which version of ThermoRawFileParser container you use?
I tried with non-dockerized 1.2.0 and it seems to work. (There is a bug though in 1.3.0 and 1.3.1 (only when -p flag is set), I will fix it today.)

Invoked as 
```
ThermoRawFileParser.exe -d D:\foo\KKL -o D:\foo\KKL -f 1 -p -e
```

Then i used `bioconductor/bioconductor_docker:latest` (R 4.0.0 and Bioconductor 3.11) and latest version of `mzR`
```
> mzR::openMSfile("20200317_KKL_CoV2_24h_5v5_F6.mzML")
Mass Spectrometry file handle.
Filename:  20200317_KKL_CoV2_24h_5v5_F6.mzML 
Number of scans:  45629 
> mzR::openMSfile("20200317_KKL_CoV2_24h_5v5_F9.mzML")
Mass Spectrometry file handle.
Filename:  20200317_KKL_CoV2_24h_5v5_F9.mzML 
Number of scans:  45369 
```

**Comment by caetera** [comment]
Version 1.3.1 is updated with the fix for the bug, I have mentioned earlier.

**Comment by higsch** [comment]
Thanks a lot!
I totally forgot to answer, sorry for this! I think I used one of the 1.3.x versions – thanks for fixing!
