### ISSUE TITLE
Conversion error: nstrument index not available for requested device

### ISSUE THREAD

**Issue by tivdnbos** [compomics/ThermoRawFileParser#74]
Hi, 

when trying to convert d6_12_hTT_I.raw to .mgf from PXD017035 (https://www.ebi.ac.uk/pride/archive/projects/PXD017035), I receive the following error message:

> 2020-04-18 23:02:26 INFO Started parsing /home/compomics/Downloads/d6_12_hTT_I.raw 2020-04-18 23:02:26 ERROR An unexpected error occured: 2020-04-18 23:02:26 ERROR System.ArgumentOutOfRangeException: Instrument index not available for requested device Parameter name: instrumentIndex 
> at ThermoFisher.CommonCore.RawFileReader.RawFileAccessBase.SelectInstrument (ThermoFisher.CommonCore.Data.Business.Device instrumentType, System.Int32 instrumentIndex) [0x00075] in <64bc662b799b40db80f0b1fa627af787>:0 
> at ThermoRawFileParser.RawFileParser.ProcessFile (ThermoRawFileParser.ParseInput parseInput) [0x00077] in <990f6d97e46b4304b64db5e738e6cd86>:0 
> at ThermoRawFileParser.RawFileParser.Parse (ThermoRawFileParser.ParseInput parseInput) [0x00176] in <990f6d97e46b4304b64db5e738e6cd86>:0 
> at ThermoRawFileParser.MainClass.RegularParametersParsing (System.String[] args) [0x008a0] in <990f6d97e46b4304b64db5e738e6cd86>:0 
> 
> Conversion complete for /home/compomics/Downloads/d6_12_hTT_I.raw
> 
> Done

Any idea what this causes?

Thanks,
Tim

**Comment by tivdnbos** [comment]
I have the same problem with MSConvert, so it might be a problem with the RAW file itself.

**Comment by caetera** [comment]
Hi @tivdnbos, the file itself seems to be corrupted, I cannot open it with vendor software as well. The error indicates that (most likely) the index for MS data was not written to the file, that can happen when RAW file acquisition was not complete, for example, when mass spectrometer crushed during the run.

**Comment by nielshulstaert** [comment]
Hi, indeed I've encountered this problem as well with some files. MSConvert also didn't work but Proteome Discoverer did.
