### ISSUE TITLE
Possibility to extract additional metadata parameters?

### ISSUE THREAD

**Issue by fi7855ar** [compomics/ThermoRawFileParser#75]
Hi, I'm looking for a way to extract more metadata out of the .raw file, for example user instrument method (like DDA or DIA), gradient, swath window size (when running swath-ms). 
Do you have a feature on ThermoRawFileParser that can get a full "metadatadump" of the run parameters?

Thanks!
// Filip

**Comment by caetera** [comment]
Hi @fi7855ar,

I am the author of the small tool https://bitbucket.org/caetera/scanheadsman/src/netcore/ that can extract most of the metadata for each scan, method extraction is supported as well (as text for all instruments and as CSV/XML for Lumoses with Tune 3.2). It is using the same libraries as ThermoRawFileParser. If you want to use method extraction on Linux/Mac you have to use .NetCore version of the tool (the link I provided above).
Please, check if it is something for you.

Best regards,
Vladimir

**Comment by fi7855ar** [comment]
Absolutely brilliant @caetera , 
I think this can be the solution for what I'm looking for; as I'm using Linux Ubuntu 18.04, I'll try the .NetCore version!
(I'll keep this thread open in case I run into any issues, and close it when I've confirmed it works)
Again thanks alot Vladimir,
//Filip

**Comment by fi7855ar** [comment]
I can report that the scanheadsman tool worked well for me to extract method metadata from raw files (using Ubuntu 18.04).
As with ThermoRawfileParser, you have to use mono platform to execute ( https://www.mono-project.com/download/stable/ )
Normally one should exeute as: mono scanheadsman.exe "path/to/rawfile" --method:CSV
But in my case it didn't work to execute the .exe file so I tried with the .dll file, which worked:
mono scanheadsman.dll "path/to/rawfile" --method:CSV
Hope it works for you guys who are in search of a good method metadata parser!
//Filip

**Comment by fi7855ar** [comment]
I can report that the scanheadsman tool worked well for me to extract method metadata from raw files (using Ubuntu 18.04).
As with ThermoRawfileParser, you have to use mono platform to execute ( https://www.mono-project.com/download/stable/ )
Normally one should exeute as: mono scanheadsman.exe "path/to/rawfile" --method:CSV
But in my case it didn't work to execute the .exe file so I tried with the .dll file, which worked:
mono scanheadsman.dll "path/to/rawfile" --method:CSV
Hope it works for you guys who are in search of a good method metadata parser!
//Filip

**Comment by caetera** [comment]
Just wanted to add, that the compiled binary seems to work also with mono (i.e. no NetCore runtime is necessary), however I failed to build the project with xbuild (Mono) and successfully built it with msbuild provided with NetCore SDK. So when recompiling NetCore SDK might be necessary.
