### ISSUE TITLE
Error tool capturing only profile MS2 for PRIDE Raw submission

### ISSUE THREAD

**Issue by ypriverol** [compomics/ThermoRawFileParser#76]
@nielshulstaert @caetera : 

We have found an "interesting" behavior (https://github.com/nf-core/proteomicslfq/issues/52) when running TRFP into one raw file from a COVID dataset. The tool only exports into the mzML the profile MS2 but not the centroid.  

The raw file is:

[03.raw](http://ftp.pride.ebi.ac.uk/pride/data/archive/2020/04/PXD018682/03.raw)

**Comment by edeutsch** [comment]
This sounds like the same bug that I emailed Niels about some time back. I don't think there was a resolution. We're interested in a resolution too. Here was the original report:

We think we have observed a peak-picking bug in ThermoRawFileParser:
Dataset: PXD013999
File: KO5.raw
 
After running:
mono /regis/sbeams/bin/ThermoRawFileParser/ThermoRawFileParser.exe -i=$name.raw -f=2 -o=./ -m=1 --metadata_output_file=$name-meta.txt
(produces a 13 GB mzML file)
 
we find that the MS2 scans are not peak-picked?
 
------- Scan 2349 header information -------
        filterLine: ITMS + p NSI r d Full ms2 458.1998@hcd35.00 [110.0000-1843.0000]
        nativeId: controllerType=0 controllerNumber=1 scan=2349
        msLevel: 2
    precursorMZ: 458.1998
       numPeaks: 25995
       scanTime: 1380.48
          lowMZ: 110.00
         highMZ: 1843.00
 
   1.  mass   110.0667  inten      12.2467
   2.  mass   110.1333  inten      12.3178
   3.  mass   110.2000  inten       6.1964
   4.  mass   110.2667  inten       0.3946
   5.  mass   110.3333  inten       0.0000
   6.  mass   110.4000  inten       0.0164
   7.  mass   110.4667  inten       0.0258
   8.  mass   110.5333  inten       0.0000
   9.  mass   110.6000  inten       0.0017
  10.  mass   110.6667  inten       0.0000
  11.  mass   110.7333  inten       0.4865
  12.  mass   110.8000  inten       4.7760
  13.  mass   110.8667  inten       5.1575
  14.  mass   110.9333  inten       0.2316
  15.  mass   111.0000  inten       0.4564
 
This would seem not to be peak-picked.
 
But when we do:
msconvert.exe --mzML --filter "peakPicking true [1,2]" -z  --32 $name.raw
(produces a 1.2 GB mzML file)
 
It does seem to peak pick these.
 
------ Scan 2349 header information -------
        filterLine: ITMS + p NSI r d Full ms2 458.1998@hcd35.00 [110.0000-1843.0000]
        nativeId: controllerType=0 controllerNumber=1 scan=2349
        msLevel: 2
    precursorMZ: 458.1998
       numPeaks: 778
       scanTime: 1380.48
          lowMZ: 110.00
         highMZ: 1843.00
 
   1.  mass   110.1202  inten      30.7610
   2.  mass   110.9578  inten      18.7097
   3.  mass   111.9478  inten      78.5293
   4.  mass   112.8041  inten      60.5399
   5.  mass   114.9097  inten     253.0165
   6.  mass   115.9375  inten     103.4101
   7.  mass   116.8930  inten      13.3500
   8.  mass   117.9243  inten      28.6867
 
Do you have ideas on how to address this?
 
It does work on most files we have, but not on this file (and its siblings)

**Comment by ypriverol** [comment]
@edeutsch we will have a look. @nielshulstaert will take a look tomorrow. The dataset I reported is actually a COVID-19 which is really important. I think is the capturing method. If @nielshulstaert can't do it, I will give a try.

**Comment by caetera** [comment]
I have seen this kind of behavior on some files with IT profile data. It seems like vendor libraries depend on centroiding provided by the instrument (it was named labels, as far as I can remember). Can it be that MSConvert falls back to its own centroiding algorithm when it cannot perform centroiding by vendor libraries?

**Comment by edeutsch** [comment]
It could be. msconvert does have its own code for that. I was vaguely under the impression that msconvert always used vendor centroiding for all Thermo data, but I have no concrete information. Should we ask Matt? He could provide a definitive answer.

**Comment by caetera** [comment]
I think I can find the solution - `Scan.ToCentroid ` method can perform centroiding of the profile spectra, if no `CentroidStream` is present in `Scan` itself. @nielshulstaert did you find this as well? (Just so I know if I need to change the code)

**Comment by nielshulstaert** [comment]
Hi @caetera thanks for the tip, I wasn't aware that method existed! Indeed there is no centroided data available for those profile scans. So should we always use this method unless the p|noPeakPicking argument is provided?

**Comment by caetera** [comment]
Hi @nielshulstaert , when testing I have found a caveat - when applied to FTMS spectra that spit `CentroidStream` by default, it will redo the centroiding and thus will give wrong results (as far as I can say, it treats centroids as profile points). I haven't tested it with spectra that are centroided in raw file. If the API will pass them as `CentroidStream` that should be fine. I should have time this evening to check how API handles the "pre-centroided" spectra.

**Comment by nielshulstaert** [comment]
Ok it makes sense not do to it on already centroided data. I have time to work on it this afternoon, I'll keep you posted on my progress.

**Comment by nielshulstaert** [comment]
Hi @caetera I've made a new branch with the changes, thermolibupgrade. I've tested it on some RAW files and it seems to work. Could you try it on an FTMS dataset? @edeutsch your example file output is a lot smaller now (the resulting MGF has the same size as an MSConvert one).

**Comment by caetera** [comment]
Hi @nielshulstaert 
During the test I can observe that only FTMS scans have CentroidStream, ITMS scans even when centroided still only have SegementedScan. The code you have added performs centroiding every time the spectrum does not have CentroidStream. I tested it on raw file with centroided ITMS (i.e. they do not have `CentroidStream` ) scans and it works correctly. Although I could not break it maybe it is better to have additional check for the case when scan has no `CentroidedStream`, but still centroided.
What do you think?

Here is a piece of code I changed in MzMlSpectrumWriter (to explain better what I mean)
 ```
if (!ParseInput.NoPeakPicking)
{
	//The spectrum to be written is going to be centroid anyway
	spectrumCvParams.Add(new CVParamType
	{
		accession = "MS:1000127",
		cvRef = "MS",
		name = "centroid spectrum",
		value = ""
	});

	if (scan.HasCentroidStream)
	// centroided stream is proviede by raw file, for example FTMS scan
	{
		var centroidStream = scan.CentroidScan;
		if (centroidStream.Length > 0)
		{
			basePeakMass = centroidStream.BasePeakMass;
			basePeakIntensity = centroidStream.BasePeakIntensity;
			lowestObservedMz = centroidStream.Masses[0];
			highestObservedMz = centroidStream.Masses[centroidStream.Masses.Length - 1];
			masses = centroidStream.Masses;
			intensities = centroidStream.Intensities;
		}
	}
	else
	{
		//if the spectrum is profile perform centroiding otherwise use it as is
		var segmentedScan = scanEvent.ScanData == ScanDataType.Profile ? Scan.ToCentroid(scan).SegmentedScan : scan.SegmentedScan;

		if (segmentedScan.PositionCount > 0)
		{
			basePeakMass = scan.ScanStatistics.BasePeakMass;
			basePeakIntensity = scan.ScanStatistics.BasePeakIntensity;
			lowestObservedMz = segmentedScan.Positions[0];
			highestObservedMz = segmentedScan.Positions[segmentedScan.PositionCount - 1];
			masses = segmentedScan.Positions;
			intensities = segmentedScan.Intensities;
		}
	}
}
else
// we requested to provide profile spectrum if possible
{
	// Get the scan statistics from the RAW file for this scan number
	var scanStatistics = _rawFile.GetScanStatsForScanNumber(scanNumber);

	basePeakMass = scanStatistics.BasePeakMass;
	basePeakIntensity = scanStatistics.BasePeakIntensity;

	// Get the segmented (low res and profile) scan data
	var segmentedScan = _rawFile.GetSegmentedScanFromScanNumber(scanNumber, scanStatistics);
	if (segmentedScan.Positions.Length > 0)
	{
		switch (scanEvent.ScanData)
		{
			case ScanDataType.Centroid:
				spectrumCvParams.Add(new CVParamType
				{
					accession = "MS:1000127",
					cvRef = "MS",
					name = "centroid spectrum",
					value = ""
				});
				break;
			case ScanDataType.Profile:
				spectrumCvParams.Add(new CVParamType
				{
					accession = "MS:1000128",
					cvRef = "MS",
					name = "profile spectrum",
					value = ""
				});
				break;
		}

		lowestObservedMz = segmentedScan.Positions[0];
		highestObservedMz = segmentedScan.Positions[segmentedScan.Positions.Length - 1];
		masses = segmentedScan.Positions;
		intensities = segmentedScan.Intensities;
	}
}
```

**Comment by nielshulstaert** [comment]
You're right @caetera it's better with the check. I've pushed the changes to the thermolibupgrade branch. Thanks for all your input, I'll release a new version on Sunday. Let me know if I missed something.

**Comment by caetera** [comment]
@nielshulstaert I have added the centroid/profile detection for PROXI format (similarly how it is performed in mzML). When there is no profile spectrum, but user request it.
Also moved few comments.

**Comment by nielshulstaert** [comment]
@edeutsch @ypriverol I've released a new version, let us know if it works.
