### ISSUE TITLE
ThermoRawFileParser not recognizing some instruments?

### ISSUE THREAD

**Issue by edeutsch** [compomics/ThermoRawFileParser#80]
Hi, we have discovered that many of our ThermoRawFileParser converted files do not have the correct instrument model encoded in them. Example:
```
    <referenceableParamGroupList count="1">
      <referenceableParamGroup id="commonInstrumentParams">
        <cvParam cvRef="MS" accession="MS:1000483" value="" name="Thermo Fisher Scientific instrument model" />
        <cvParam cvRef="MS" accession="MS:1000529" value="SN03468B" name="instrument serial number" />
      </referenceableParamGroup>
    </referenceableParamGroupList>
    <softwareList count="1">
      <software id="ThermoRawFileParser" version="1.3.0-pre">
        <cvParam cvRef="MS" accession="MS:1000799" value="ThermoRawFileParser" name="custom unreleased software tool" />
      </software>
    </softwareList>
```

The instrument model is not provided, just the ambiguous parent term.
For the same file, msconvert provides this:
```
    <referenceableParamGroupList count="1">
      <referenceableParamGroup id="CommonInstrumentParams">
        <cvParam cvRef="MS" accession="MS:1001742" name="LTQ Orbitrap Velos" value=""/>
        <cvParam cvRef="MS" accession="MS:1000529" name="instrument serial number" value="SN03468B"/>
      </referenceableParamGroup>
    </referenceableParamGroupList>
    </sampleList>
    <softwareList count="2">
      <software id="Xcalibur" version="2.7.0">
        <cvParam cvRef="MS" accession="MS:1000532" name="Xcalibur" value=""/>
      </software>
      <software id="pwiz" version="3.0.20155">
        <cvParam cvRef="MS" accession="MS:1000615" name="ProteoWizard software" value=""/>
      </software>
    </softwareList>
```

This seems to happen for both instruments:
   "name": "LTQ Orbitrap Velos"
   "name": "LTQ Orbitrap Elite"

Would you add those instruments to ThermoRawFileParsers list of recognized instruments?
The above example comes from the raw files in:
ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2015/02/PXD000660

**Comment by caetera** [comment]
Hi Erik,

thank you for reporting the problem. The instrument in the files you refrence is provided as "Orbitrap Velos Pro", that does not have a specific CV term, the closest one is "LTQ Orbitrap Velos".
As a fix I added "Orbitrap Velos Pro" resolving to "LTQ Orbitrap Velos", but none of the the referenced files was from Orbitrap Elite, thus I will need an example to add Oribtrap Elite in the same way.

**Comment by edeutsch** [comment]
Thanks for this. I have requested a new term for LTQ Orbitrap Velos Pro:
https://github.com/HUPO-PSI/psi-ms-CV/pull/31/files
Please review that PR.

As for the Orbitrap Elite, please see the first few files here:
ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2019/08/PXD013646
Apparently the "LTQ Orbitrap Elite" and the "Orbitrap Elite" are the same instrument, just different names.

**Comment by caetera** [comment]
I have updated the mapping in ThermoRawParser with new terms. I will talk with @nielshulstaert to get the new release.

**Comment by edeutsch** [comment]
Any news on a new release?

**Comment by chambm** [comment]
I've added these in msconvert as well. The Exploris 120 and 240 and the `Orbitrap ID-X` too. (NB for @caetera: that is the instrument model string to check for)

**Comment by edeutsch** [comment]
Thanks, @chambm !

@caetera , new term is here:
https://github.com/HUPO-PSI/psi-ms-CV/pull/37/files

**Comment by caetera** [comment]
Added Orbitrap ID-X in ded9953 

Sorry, no updates on the new release. I talked with @nielshulstaert to review my changes (two pair of eyes are better, than one) and do a release some time ago, but I haven't heard from him since then.

**Comment by edeutsch** [comment]
okay, thank you! We're still using 1.3.0-pre (or some version of that if there's more than one) but it would be super nice to have an official 1.3.0 or whatever version with these changes in there and whatever else has happened. Thanks!

**Comment by caetera** [comment]
Release is published.
