### ISSUE TITLE
writing SPS mz to mzML

### ISSUE THREAD

**Issue by pavel-shliaha** [compomics/ThermoRawFileParser#81]
This reqest is very technical so please let me know if its not clear so I can elaborate or discuss it via a zoom meeting. 

We would like to analyse some MS3 TMT data and one of the important outputs, that determines the quality of a particular peptide quantitation is the proportion of MS2 fragments selected by SPS for MS3 fragmentation, that have been assigned to a meanignful fragment of the identified peptide. E.g. PD now returns a number like 4/10 of fragments selected for MS3 are identified as fragments from the peptide selected for DDA.

The data is contaned in the scan header of MS3 scans, under SPS masses. Could you please change the software so it exportsthis data

**Comment by caetera** [comment]
Hi Pavel,

The solution that can be implemented is to include SPS Masses present in Scan Trailer into `<spectrum>` element as `<userParam>`. As I can, see there is no ontology term for this kind of information yet (Could you confirm it @edeutsch ?). Will this work for you?
However, the matching of SPS masses to fragments should be performed on a later stage of data processing. ThermoRawFileParser's scope is to produce files in open formats.

As a quick workaround solution, you can use your _old friend_ ScanHeadsman - the trailer information is exported and can be mapped back using the native id or scan number.

**Comment by caetera** [comment]
I have made first implementation of SPS masses export - 85d300a . The masses are exported as additional precursor elements of a corresponding scan. Msconvert does it in a similar way. Unfortunately, it seems like the isolation width used for SPS masses is not stored in the raw file (or, at least, I could not find an obvious way to fish it out). Please, let me know, if it works for you.

**Comment by caetera** [comment]
SPS is included in the latest release - 1.3.2
