### ISSUE TITLE
How to export instrument methods in meta data?

### ISSUE THREAD

**Issue by 01joy** [compomics/ThermoRawFileParser#86]
Hi developer,

I want to know is ThermoRawFileParser able to export instrument methods of hundreds of raw files in batch mode? 

I have more than 100+ raw files downloaded from pride database, each of them has different instrument methods, I want to export the detailed instrument methods from all these raw files, can we do it?

For example the instrument methods below from Xcalibur:

![image](https://user-images.githubusercontent.com/8603895/88879002-cb20c200-d25b-11ea-9c57-5e0eb4ebd445.png)

But the meta data exported by ThermoRawFileParser has no these information (see below):

```
Created by=[MS, MS:1000529, created_by, Orbitrap_Lumos]
Number of instruments=4
Description=
Instrument model=[MS, MS:1000494, Thermo Scientific instrument model, Orbitrap Fusion Lumos]
Instrument name=Orbitrap Fusion Lumos
Instrument serial number=[MS, MS:1000529, instrument serial number, FSN20113]
Software version=[NCIT, NCIT:C111093, Software Version, 2.1.1565.18]
Firmware version=
Units=None
Mass resolution=[MS, MS:1000011, mass resolution, 0.500]
Number of scans=19123
Scan range=1;19123
Scan start time=[MS, MS:1000016, scan start time, 0.00]
Time range=0.00;90.00
Mass range=100.0000;2000.0000

#Sample information
Sample name=
Sample id=27
Sample type=Unknown
Sample comment=
Sample vial=RG1
Sample volume=0
Sample injection volume=3.5
Sample row number=2
Sample dilution factor=1
```

**Comment by caetera** [comment]
Hi @01joy ,

ThermoRawFileParser does not support method extraction in metadata. You can extract methods in plain text and (only some information) to CSV and XML, using different tool - https://bitbucket.org/caetera/scanheadsman/src/netcore/. Hope it will help.

#75

**Comment by 01joy** [comment]
Hi @caetera ,

Thank you very much, I have tried your recommended tool, the scanheadsman, it is a very fantastic tool, it can export the detailed info for each ms2 scan, that's what I want. Thank you very much.
