### ISSUE TITLE
Filter by MS level in mgf output + MS3->MS2 mapping

### ISSUE THREAD

**Issue by MatthewThe** [compomics/ThermoRawFileParser#88]
First of all, great package!

We have several RAW files with MS3 spectra, but in the current mgf output there doesn't seem to be a way to distinguish between MS2 and MS3 spectra. Ideally, we would want a command line argument to only write MS2 or MS3 spectra to the mgf file, as well as information on which MS2 scan the MS3 scan belongs to (present in the `precursor` tag in the mzML).

Would it be possible to implement this feature, or otherwise point to the relevant portion of code?

**Comment by caetera** [comment]
Just wondering why not using mzML that has precursor information? ;)
It seems like there is no valid field in MGF that can hold precursor scan information - I have to create one, thus, the resulting MGF is not standard anymore. I hope it won't break anything downstream. The implementation is not very pretty, since I have just reused code from mzML part. When flag `-P|--mgfPrecursor` is present, MGF files contain PRECURSORTITLE line that has scan id in native format for precursor scan. The update is committed - 6ab19c4

**Comment by MatthewThe** [comment]
That's awesome, thanks a lot!

You're completely right that we could use mzML directly, but for the moment we like the combination of being able to easily extract TMT reporter intensities without having to use an XML parser and processing the files with regular search engines.

For the moment we can probably build this ourselves, but do you have any idea/plan when this will be merged and/or released?

**Comment by caetera** [comment]
On a second thought I think it would be better to put precursor information into the title field, i.e. something like
`TITLE=controllerType=0 controllerNumber=1 scan=5 [PRECURSOR=controllerType=0 controllerNumber=1 scan=4]` In that case the MGF should be standardized again. Please, let me know if it works for you.
Regarding, the release, I will try to push it ASAP, but it might be not fast at all. I prefer if other developers will look at the code as well. It might take some time. More eyes - better chance not to introduce any bugs.

**Comment by MatthewThe** [comment]
That sounds like a good idea, that will definitely work for us as well.

I understand it might take a while for the release, no problem!

**Comment by caetera** [comment]
Ok. I moved it to the TITLE - 60062765

**Comment by caetera** [comment]
Pushed into version 1.3.1 and released

**Comment by MatthewThe** [comment]
Fantastic, thanks again! This really helps for our project.

**Comment by caetera** [comment]
I have found a bug in mzML processing, thus, release was updated.
