### ISSUE TITLE
Include Reference and Exception Peaks

### ISSUE THREAD

**Issue by ozgurdemir** [compomics/ThermoRawFileParser#90]
Hi there,

thx for this nice library. By default the thermo RawFileReader hides exception and reference peaks from FTMS capable instruments. According to the RawFileReader documentation these can be activated via:

```
// Enable the include reference and exception data
rawFile.IncludeReferenceAndExceptionData = true;
```

A github search did not reveal this line in the current code base of ThermoRawFileParser so I assume the written files do not contain the reference and exception peaks. 
Is it possible to add a flag which controls the inclusion of reference and exception peaks to ThermoRawFileParser? In our case one of the reference peaks coincides with a m/z of interest.

**Comment by caetera** [comment]
Hi @ozgurdemir ,

yes, you are right - reference and exception peaks are not included.
It can be done, though.

**Comment by ozgurdemir** [comment]
@caetera thx. the question is should they be included by default. so just setting the 

`rawFile.IncludeReferenceAndExceptionData = true;`

of should the user have the posibility to set it via a command line flag. The 2nd solution makes usage a bit more complicated and the implementation, too.

**Comment by ozgurdemir** [comment]
So since I need this if it's ok I'd open up a pull request setting the flag to true and add a comment in the readme that by default reference and exception peaks are included.

**Comment by caetera** [comment]
I think, it is better to keep the default behavior as it is now. Your case is rather an exception, IMO, thus, I would prefer the second solution.
If you can implement it and make a pull request I will be happy to review/merge it, otherwise, I can implement it later.

**Comment by ozgurdemir** [comment]
I agree that it is the better solution. However, I'm not familiar with the code base. So setting up the dev env and making the changes which are probably rather small will take me some time. What would be your timeline @caetera to implement this?

**Comment by caetera** [comment]
837995a implements the change;
new console key `-x|--includeExceptionData` adds exception and reference data.
Please let me know if it works for you.
You can use semi-official docker container if necessary https://hub.docker.com/r/caetera/thermorawfileparser/

**Comment by ozgurdemir** [comment]
@caetera wow that was quick. thx a lot for the implementation. really appreciated. I quickly tried the docker container and it seems to work.

**Comment by ozgurdemir** [comment]
I'm gonna close this issue as it has been fixed.

**Comment by caetera** [comment]
Great. I will include this update in the next release.

**Comment by ozgurdemir** [comment]
@caetera any clue when the next release will be?

**Comment by caetera** [comment]
@ozgurdemir It might take some time, let's say a week or two. There might be some minor changes in other parts of the tool.
