### ISSUE TITLE
What's the difference between -f=1 and -f=2? 

### ISSUE THREAD

**Issue by rolivella** [compomics/ThermoRawFileParser#93]
Hi, I'm using your library in a pipeline I'm developing and I would like to know the excact meaning of "indexed mzML" in one of the optional parameters: 

`-f, --format=VALUE         The spectra output format: 0 for MGF, 1 for mzML, 2 for indexed mzML`

I'm processing complex Human samples and I obtain very different numbers for protein and peptide identifications when I change this parameter from 1 to 2. 

When is recommended to use it or not? 

Thank you!

**Comment by nielshulstaert** [comment]
Hi,

The indexed mzML has an additional index table at the bottom of the file for faster access to spectra, if the software you use supports it. There shouldn't be any difference in number of scans between the 2 formats. If you do notice a difference, please share the raw file in question so I can try to convert it.

Thanks for using the TRFP

**Comment by rolivella** [comment]
Thanks @nielshulstaert . I think that in that case there's something wrong regarding the workflow that comes after the conversion. I'll check it and come back to you if necessary.
