### ISSUE TITLE
Output to stdout?

### ISSUE THREAD

**Issue by tomas-pluskal** [compomics/ThermoRawFileParser#99]
Hi, is it possible to specify stdout as the destination? 
If not, would it be possible to add such feature? 
It would be great for processing the output files (e.g., mzML) using pipes without the necessity to store the mzML in a separate file.

**Comment by caetera** [comment]
Hi @tomas-pluskal 

thank you for your interest in ThermoRawFileParser. On Linux one can use `/dev/stdout` as an argument for `-b` (single file output), you should also use `-l=0` (no logging) to get "clean" output. Please, let me know if it works for you.

**Comment by tomas-pluskal** [comment]
Thanks for the tip, but actually I would like to use this option on macOS and on Windows as well.

**Comment by caetera** [comment]
According to this thread - https://unix.stackexchange.com/questions/338667/unix-systems-without-dev-stdin-dev-stdout-and-dev-stderr - `/dev/stdout` should work on the majority of POSIX-compliant systems, including MacOS. I do not have any Mac to test it, but it worth trying. There are some aliases that can work as well, `/proc/self/fd/1` and `/dev/fd/1`. On Windows the situation is a bit more complicated, though, there are some indications that the same trick will work in Cygwin environment (I can test it later).
Note, however, that stdout won't allow for seek operations, and, thus, for example, indexed mzML won't be working.
I will add more unifed output to stdout as a feature request, though.

**Comment by tomas-pluskal** [comment]
Thanks!

**Comment by caetera** [comment]
The new key `-s` `--stdout` directs file output to standard output. It implies silent logging (i.e. the value of `-l` key even if it exists is ignored and `-l=0` is used instead) and invalidates, obviously, `-o` and `-b` keys (i.e. the program will exist with error).
You can get the beta version using the link below or compile it from the source (f116a85) (I have tested it on Linux and Windows, but do not have Mac)
https://syddanskuni-my.sharepoint.com/:u:/g/personal/vgor_bmb_sdu_dk/EQUDjsllf0JLjKesfCMamD8BMWQ5XD2pZG_GSX7rvV87Iw?e=Zj3rfi

**Comment by tomas-pluskal** [comment]
Thanks a lot. I just tested it using Mono on macOS, works like a charm!

**Comment by caetera** [comment]
Good to hear, this feature will be added to the next release.

**Comment by nielshulstaert** [comment]
This has been added to release 1.3.3
